# -*- coding: utf-8 -*-
"""
rebuild_items_b.py — second replacement wave for rebuild_bank.py.

Parts 1 and 2 of the old bank were a mix of general-English drill material
(pets, weather, shopping, personal life) that has nothing to do with the TOEIC
workplace register. Every item below replaces such a question with a
business-context Part 5 item, keeping the original testing point where it makes
sense (word form, preposition, verb tense, collocation ...).

Format:  id: (sentence with ____, [four options], correct option)
"""

PART1 = {
    5: ("The travel agency's brochure features ____ photographs of the island resorts.",
        ["color", "colored", "colorful", "coloring"], "colorful"),
    6: ("The new accounting software is ____ reliable as the system we replaced.",
        ["like", "as", "so", "too"], "as"),
    10: ("The technician ____ the safety fence to reach the faulty control panel.",
         ["climbed over", "climbed", "climbed up", "climbed on"], "climbed over"),
    12: ("The beverage company holds a patent on its ____ formula for the sports drink.",
         ["special", "especial", "specially", "especially"], "special"),
    13: ("____ unexpected power failures, the data centre is equipped with two backup generators.",
         ["Having avoided", "Avoiding", "To avoid", "Avoid"], "To avoid"),
    16: ("After his transfer to the regional office, Mr. Amos ____ visits the head office.",
         ["hardly", "hardly never", "hardly ever", "hard ever"], "hardly ever"),
    19: ("Last week, the supplier ____ a written warning about the late deliveries.",
         ["receives", "received", "was receiving", "had to receive"], "received"),
    20: ("Her technical skills, experience ____ attention to detail make Ms. Ito an ideal candidate.",
         ["or", "and", "also", "but"], "and"),
    21: ("The supervisor reported the safety ____ to the plant manager in the evening.",
         ["happened", "incident", "incidental", "opportune"], "incident"),
    23: ("The director greatly ____ the extra hours the team put in last week.",
         ["thank", "appreciate", "grateful", "thankful"], "appreciate"),
    28: ("The new conference chairs are a lot ____ than the old ones.",
         ["more comfortable", "comfortable", "more comfort", "the most comfortable"], "more comfortable"),
    30: ("The receptionist could not see ____ at the front desk this morning.",
         ["nobody", "somebody", "anybody", "who"], "anybody"),
    31: ("A side ____ of the new trade policy was a sharp rise in shipping costs.",
         ["effect", "affect", "result", "factor"], "effect"),
    33: ("Please remember to turn ____ the lights in the meeting room when you leave.",
         ["in", "off", "under", "over"], "off"),
    38: ("Since her promotion, Ms. Park has worked ____ than her colleagues.",
         ["hard", "harder", "hardest", "hardly"], "harder"),
    39: ("Employees who feel unwell should give ____ a day of rest.",
         ["theirs", "themselves", "himself", "oneself"], "themselves"),
    41: ("There is a chance the shipment ____ be delayed by the storm.",
         ["can", "may", "are", "should"], "may"),
    44: ("The sales director is going to ____ to Singapore next month.",
         ["traveling", "take a trip", "taking a trip", "take a travel"], "take a trip"),
    47: ("The first quarter was not ____ profitable as the board had expected.",
         ["that", "so", "as", "very"], "as"),
    49: ("The keynote speaker's presentation was extremely ____.",
         ["interests", "interested", "interestingly", "interesting"], "interesting"),
    53: ("The firm's oldest factory is over eighty ____.",
         ["old years", "years old", "years ancient", "year aged"], "years old"),
    54: ("The company's policy on remote work is very ____ from the one in our branch.",
         ["differ", "different", "differing", "differentiate"], "different"),
    55: ("Staff should not contact clients directly ____ the account manager approves it.",
         ["besides", "unless", "accept", "if"], "unless"),
    62: ("Managers know that if they want a task ____ properly, they must delegate it clearly.",
         ["have done", "done", "to do", "did"], "done"),
    64: ("Ms. Bell's duties at the agency include planning events, drafting letters and ____ clients.",
         ["to greet", "greeting", "greeted", "greets"], "greeting"),
    66: ("It is ____ said that customers remember good service longer than low prices.",
         ["many", "much", "usual", "often"], "often"),
    67: ("The founder waited until his ____ son had joined the firm before retiring.",
         ["young", "younger", "youngest", "most young"], "youngest"),
    68: ("The board agreed that this is the best time to invest in research and ____.",
         ["develop", "developed", "developing", "development"], "development"),
    72: ("____ the client confirms the order today, the goods will be shipped on Monday.",
         ["As", "If", "Probably", "As if"], "If"),
    78: ("The manager ____ proposal won the contract was praised by the board.",
         ["whom", "who", "which", "whose"], "whose"),
    79: ("The ____ office on the corner was known to everyone in the neighbourhood.",
         ["Small green", "A green small", "The green small", "The small green"], "The small green"),
    80: ("Only ____ of the applicants had previous experience in logistics.",
         ["a few", "a little", "much", "every"], "a few"),
    83: ("____ the enquiries we receive come from overseas clients.",
         ["Much", "Almost of", "Almost", "Most of"], "Most of"),
    85: ("Few analysts predicted the ____ growth of the online retail market.",
         ["drama", "dramatical", "dramatic", "dramatically"], "dramatic"),
    91: ("The client would not have complained if the invoice ____ correct.",
         ["will be", "was", "should be", "had been"], "had been"),
    93: ("There are not ____ employees who are willing to work night shifts.",
         ["many", "much", "a few", "a lot"], "many"),
    97: ("All staff are expected to show respect ____ the company's clients.",
         ["to", "through", "for", "at"], "for"),
}

PART2 = {
    102: ("The press release ____ by the communications manager.",
          ["wrote", "was written", "was writing", "were written"], "was written"),
    103: ("When customers submit a request, our agents always get back to ____ within one day.",
          ["them", "him", "their", "they"], "them"),
    104: ("Although the branch opens late, it ____ not stay open on Sundays.",
          ["do", "does", "can", "did"], "does"),
    106: ("The warehouse team ____ delivers within 24 hours, so customers rarely complain.",
          ["always", "never", "hardly", "rarely"], "always"),
    108: ("The training session was so long ____ several participants left before the end.",
          ["so", "as", "that", "then"], "that"),
    110: ("The visitors asked ____ they could leave their luggage during the tour.",
          ["for", "why", "where", "what"], "where"),
    111: ("Many candidates become ____ when asked to speak before a panel.",
          ["nervously", "nervy", "nervousness", "nervous"], "nervous"),
    117: ("____ his main job, Mr. Adeyemi runs a small delivery business.",
          ["Aside", "Part of", "Beside", "Besides"], "Besides"),
    119: ("The sign outside states that the office ____ is available for lease.",
          ["around", "far", "next door", "near"], "next door"),
    120: ("____ of the safety rules is part of the induction week for new staff.",
          ["Memories", "Remember", "Memorable", "Memorization"], "Memorization"),
    121: ("The agency requested an album of the designer's most ____ work.",
          ["later", "latest", "late", "lately"], "latest"),
    143: ("Analysts say that online sales have ____ changed the way retailers reach customers.",
          ["accusingly", "dramatically", "sensationally", "mainly"], "dramatically"),
    152: ("The new trade ____ between the two countries takes effect in January.",
          ["treaty", "amenity", "aid", "mitigation"], "treaty"),
    153: ("Investors were ____ the sudden drop in share prices.",
          ["horrified with", "horrified of", "horrified in", "horrified by"], "horrified by"),
    155: ("The security guard found the night porter ____ at his desk.",
          ["fast asleep", "quick asleep", "run asleep", "big asleep"], "fast asleep"),
    156: ("Managers should ____ at least two hours a week to staff training.",
          ["provoke", "excite", "relieve", "allot"], "allot"),
    157: ("____ landing the biggest contract of the year!",
          ["Congratulations on", "Congratulations for", "Congratulations with", "Congratulations in"], "Congratulations on"),
    158: ("The chef explained that the tuna is served ____ and must be kept at very low temperatures.",
          ["tentative", "raw", "bounteous", "mean"], "raw"),
    159: ("It took the company three years to ____ the effects of the recession.",
          ["get away", "get off", "get over", "get out"], "get over"),
    160: ("There will be ____ time for questions after the presentation.",
          ["cramped", "spacious", "ample", "swollen"], "ample"),
    161: ("The staffing shortage at the factory is ____.",
          ["losing it", "turning on", "getting worse and worse", "taking a look at"], "getting worse and worse"),
    162: ("I understand your concern, Ms. Lee, but I have to ____ the board on this matter.",
          ["give in", "feel up to", "go along with", "pull through"], "go along with"),
    163: ("The agency ____ any project that involves sustainable design.",
          ["takes up", "takes on", "takes in", "takes over"], "takes on"),
    165: ("We ____ an opportunity to discuss the proposal in person.",
          ["look forward to", "screw out of", "go in for", "put up with"], "look forward to"),
    166: ("The vendor ____ the firm out of a large deposit and then disappeared.",
          ["backed", "cheated", "turned", "looked"], "cheated"),
    167: ("The manager never ____ his staff, even when they made mistakes.",
          ["felt up to", "talked down to", "got over with", "went along with"], "talked down to"),
    168: ("The supplier was accused of ____ its customers by overcharging for spare parts.",
          ["cheating", "cheated", "cheat", "cheats"], "cheating"),
    169: ("The security guard ____ the intruder and caught him near the gate.",
          ["went after", "went off", "went by", "went on"], "went after"),
    170: ("New employees are encouraged to look ____ unfamiliar terms in the company glossary.",
          ["after", "for", "up", "into"], "up"),
    171: ("Her extensive experience more than ____ for her lack of formal qualifications.",
          ["compensates", "trims", "chases", "allures"], "compensates"),
    172: ("The old shelving unit ____ under the weight of the boxes.",
          ["crawled", "craved", "crammed", "collapsed"], "collapsed"),
    173: ("The court found the former treasurer ____ of all charges.",
          ["unlawful", "crisp", "innocent", "hoarse"], "innocent"),
    174: ("The region's farmers were ____ by drought for three seasons.",
          ["crucified", "afflicted", "killed", "cruised"], "afflicted"),
    176: ("Several pages had been ____ out of the confidential file.",
          ["sliced", "diced", "ripped", "mowed"], "ripped"),
    177: ("Water from the reservoirs is pumped to the ____ farmland in the south.",
          ["soaked", "arid", "drenched", "water-logged"], "arid"),
    178: ("If the wiring fault is not repaired, the consequences can prove ____.",
          ["fatal", "obsolete", "alive", "resplendent"], "fatal"),
    179: ("The CEO spoke with surprising ____ about the company's losses.",
          ["decision", "hallucination", "fitness", "candor"], "candor"),
    180: ("This detergent is excellent for removing ink ____ from cotton shirts.",
          ["anagrams", "decorations", "stains", "etiquettes"], "stains"),
    182: ("The band rented ____ for the evening performance at the hotel.",
          ["an amplified guitar", "an engrossed guitar", "an abnegated guitar", "an exposed guitar"], "an amplified guitar"),
    183: ("The staff complained about the ____ behaviour of the new supervisor.",
          ["intrinsic", "innate", "odious", "extolling"], "odious"),
    185: ("The keynote speaker spent an hour ____ on the benefits of green energy.",
          ["stocking", "adorning", "accounting", "expounding"], "expounding"),
    186: ("The visitors were shown a ____ meeting room with one small window.",
          ["passive", "pungent", "gloomy", "covetous"], "gloomy"),
    187: ("A ____ wind blew across the construction site all afternoon.",
          ["biting", "savory", "caustic", "cranky"], "biting"),
    188: ("The engineer ____ her career to developing safer machinery.",
          ["bent", "coupled", "devoted", "associated"], "devoted"),
    189: ("The company built its new plant in a ____ border town.",
          ["permissible", "removed", "parted", "remote"], "remote"),
    190: ("An audience of 300 clients warmly ____ the CEO's closing speech.",
          ["applauded", "adopted", "naturalized", "loaded"], "applauded"),
    191: ("Colleagues complained that his ____ comments lowered morale in the office.",
          ["sarcastic", "arctic", "charitable", "avid"], "sarcastic"),
    192: ("Having leased the office, the start-up could not afford to ____ it.",
          ["furnish", "recline", "slump", "follow"], "furnish"),
    193: ("The chef apologized that the beef was ____ and offered to bring a new dish.",
          ["cutesy", "quaint", "insincere", "overdone"], "overdone"),
    194: ("The committee ____ the supplier's first offer as too expensive.",
          ["rejected", "swallowed", "submitted", "yielded"], "rejected"),
    195: ("All new staff are made ____ of the safety regulations during induction.",
          ["keen", "attentive", "aware", "eager"], "aware"),
    196: ("The gift shop sells silk scarves embroidered with ____ patterns.",
          ["elaborate", "severe", "sober", "acrid"], "elaborate"),
    197: ("New documents have ____ the second witness's account of the accident.",
          ["confessed", "asserted", "confirmed", "owned"], "confirmed"),
    198: ("The accountant ____ his pursuers by escaping through a service exit.",
          ["eluded", "backed off", "regressed", "returned"], "eluded"),
    200: ("The crowd went ____ as soon as the winner stepped onto the stage.",
          ["ornate", "tasteless", "sane", "wild"], "wild"),
}

REST = {}
REST.update(PART1)
REST.update(PART2)

PART3 = {
    201: ("The invoices have already been sent to the client, ____?",
          ["haven't they", "do they", "have they", "don't they"], "haven't they"),
    202: ("Ms. Ferris ____ at the new branch office yesterday.",
          ["repaired the printer", "had repaired the printer", "had the printer repaired", "was repairing"], "had the printer repaired"),
    203: ("The group ____ its main competitor for $2 billion last year.",
          ["procured", "obtained", "possessed", "acquired"], "acquired"),
    205: ("The employee received compensation for the injuries ____ by the faulty machine.",
          ["inflicted", "given", "taken", "dealt"], "inflicted"),
    209: ("The delay was ____ by the sudden shortage of raw materials.",
          ["aggravated", "irritated", "annoyed", "angered"], "aggravated"),
    211: ("The purchase order covers ____ of premium coffee beans.",
          ["one and half kilo", "one and a half kilo", "one and half kilos", "one and a half kilos"], "one and a half kilos"),
    212: ("There was ____ time for consultation before the deadline.",
          ["little", "a little", "few", "a few"], "little"),
    215: ("Our department ____ responsible for all overseas accounts.",
          ["are", "were", "has", "is"], "is"),
    216: ("The firm hired ____ to manage the front desk.",
          ["a little nice assistant", "a nice little assistant", "an assistant nice and little", "an assistant little and nice"], "a nice little assistant"),
    217: ("____ details will be available after the contract is signed.",
          ["Far", "Farther", "Further", "Farthest"], "Further"),
    218: ("Mr. Todd has been with the firm longer than ____.",
          ["mine", "me", "my", "I"], "I"),
    219: ("Competition in the smartphone market is getting ____.",
          ["strong and strong", "stronger and stronger", "more and more strong", "strongest and strongest"], "stronger and stronger"),
    221: ("The airline issued a statement explaining the ____ the delay.",
          ["reason of", "reason in", "reason with", "reason for"], "reason for"),
    223: ("The designer showed the board some ____ the new packaging.",
          ["photographs with", "photographs on", "photographs by", "photographs of"], "photographs of"),
    224: ("There has been a sharp ____ the number of online orders this year.",
          ["increase on", "increase in", "increase by", "increase with"], "increase in"),
    225: ("The ____ the fire at the warehouse is still unknown.",
          ["cause with", "cause for", "cause of", "cause on"], "cause of"),
    226: ("The main ____ working from home is the time saved on commuting.",
          ["advantage of", "advantage in", "advantage with", "advantage on"], "advantage of"),
    227: ("The vendor sent us a ____ the outstanding balance.",
          ["check of", "check for", "check on", "check with"], "check for"),
    228: ("Our firm has built a strong ____ its overseas suppliers.",
          ["relationship to", "relationship with", "relationship by", "relationship in"], "relationship with"),
    229: ("The intern was given a detailed ____ the production facility.",
          ["map with", "map in", "map at", "map of"], "map of"),
    231: ("____ two holes in the top left corner of each form.",
          ["Do", "Drill", "Bore", "Punch"], "Punch"),
    236: ("____ the lever clockwise to raise the loading platform.",
          ["Break", "Fold", "Swing", "Turn"], "Turn"),
    237: ("Do not move the ____ passenger until the paramedics arrive.",
          ["widowed", "damaged", "victimized", "injured"], "injured"),
    239: ("Add a ____ of salt to the sauce before serving.",
          ["finger", "pinch", "drop", "squeeze"], "pinch"),
    240: ("Are you ____ joining our team as a part-time analyst?",
          ["interested to", "interested with", "interested on", "interested in"], "interested in"),
    241: ("She greeted the clients with a ____ smile.",
          ["big", "strong", "large", "massive"], "big"),
    242: ("The delivery driver ____ his arm while unloading the van.",
          ["ruined", "degraded", "broke", "failed"], "broke"),
    243: ("Yesterday we called a ____ to fix the leak in the staff kitchen.",
          ["carpenter", "mechanic", "janitor", "plumber"], "plumber"),
    244: ("____ a word in the glossary if you do not understand it.",
          ["Look", "Look up", "Look after", "Look for"], "Look up"),
    245: ("____ the incorrect figures and write the new ones above them.",
          ["Cross out", "Erase out", "Delete out", "Kick out"], "Cross out"),
    247: ("Drivers must be especially ____ when the roads are wet.",
          ["careful", "creative", "reliable", "suitable"], "careful"),
    248: ("I locked the office door, but I lost the key, so I could not ____ it the next morning.",
          ["unfold", "uncover", "unpack", "unlock"], "unlock"),
    249: ("Ms. Alvarez is in her car on the way to the conference. She ____.",
          ["has driven to the conference", "is driving to the conference", "drives to the conference", "drove to the conference"], "is driving to the conference"),
    252: ("Business ____ constant change.",
          ["was series of", "were series of", "are a series of", "is a series of"], "is a series of"),
    254: ("____ nominated Ms. Cho as the new sales director.",
          ["Them", "Their", "Theirs", "They"], "They"),
    256: ("The presenter could not speak ____ because of a sore throat.",
          ["good", "better", "well", "best"], "well"),
    257: ("The warehouse ____.",
          ["stood on the hill, new and empty", ", new and empty, stood on the hill", "new and empty stood on the hill", "stood on the hill new and empty"], "stood on the hill, new and empty"),
    259: ("We met the supplier ____ at the trade fair, not by arrangement.",
          ["by chance", "through chance", "in chance", "with chance"], "by chance"),
    262: ("The auditors want to question a manager in ____ the missing funds.",
          ["connection to", "connection about", "connection with", "connection for"], "connection with"),
    263: ("There is no ____ a second approval for orders under $500.",
          ["need for", "need with", "need to", "need about"], "need for"),
    264: ("The engineers hope to find a ____ the production problem.",
          ["solution on", "solution to", "solution in", "solution for"], "solution to"),
    265: ("The report describes some ____ the two accounting systems.",
          ["differences with", "differences in", "differences between", "differences on"], "differences between"),
    266: ("Management was surprised at her ____ the proposal.",
          ["reaction in", "reaction on", "reaction to", "reaction with"], "reaction to"),
    267: ("Thank you for the reference. It was very ____ to help me.",
          ["kind of you", "kind to you", "kind with you", "kind in you"], "kind of you"),
    268: ("His ____ his new duties is very positive.",
          ["attitude with", "attitude on", "attitude in", "attitude to"], "attitude to"),
    269: ("It is unprofessional to get ____ minor setbacks.",
          ["angry at", "angry about", "angry with", "angry for"], "angry about"),
    272: ("The support team has effective ways of ____ difficult complaints.",
          ["writing", "learning", "including", "dealing"], "dealing"),
    273: ("Ms. Nolan is able to ____ her concentration during long negotiations.",
          ["keep", "make", "do", "have"], "keep"),
    274: ("Good managers ____ staff who exceed their targets.",
          ["reward", "find", "describe", "experience"], "reward"),
    275: ("All employees must ____ their timesheets on time.",
          ["prioritize", "submit", "review", "disturb"], "submit"),
    278: ("Employees are encouraged to take ____ breaks during long shifts.",
          ["easy", "serious", "regular", "faithful"], "regular"),
    280: ("Trade ____ in the region after the new port opened.",
          ["occupied", "flourished", "invented", "proclaimed"], "flourished"),
    281: ("The water ____. Could you turn off the machine?",
          ["has boil", "boils", "is boiling", "boiled"], "is boiling"),
    282: ("The company has a ____ corporate culture with its own rituals and language.",
          ["distinct", "tempting", "temperate", "wild"], "distinct"),
    283: ("Our clients ____ faster service at a lower price.",
          ["have wanted", "wanting", "are wanting", "want"], "want"),
    284: ("Many engineers ____ to the region to work in the new technology hub.",
          ["cultivated", "filled", "immigrated", "deposited"], "immigrated"),
    286: ("The company enjoyed a long ____ under its founding chairman.",
          ["prize", "resources", "climate", "reign"], "reign"),
    287: ("At 10.30 yesterday the board ____ the quarterly figures.",
          ["discussed", "was discussing", "were discussing", "has discussed"], "was discussing"),
    288: ("The family ____ has controlled the group for four generations.",
          ["democracy", "communism", "dynasty", "location"], "dynasty"),
    289: ("Mr. Bright is looking for his badge. He cannot find it. He ____ it.",
          ["lost", "was losing", "had lost", "has lost"], "has lost"),
    290: ("The plant manager arrived ____ 5 o'clock to inspect the production line.",
          ["at", "in", "on", "by"], "at"),
    291: ("Mr. Cardoso ____ a logistics company that now operates in six countries.",
          ["bounded", "positioned", "established", "traced"], "established"),
    292: ("The audit team arrived ____ Friday.",
          ["on", "in", "at", "from"], "on"),
    293: ("After the merger, English became the ____ language of the group.",
          ["united", "strong", "high", "chief"], "chief"),
    294: ("The new warehouse opened ____ October.",
          ["since", "at", "on", "in"], "in"),
    295: ("The founder ran the company like a ____, ignoring all advice.",
          ["actor", "priest", "dictator", "peasant"], "dictator"),
    296: ("The firm was founded ____ 1968.",
          ["on", "in", "at", "for"], "in"),
    297: ("There is ____ competition for qualified engineers in the region.",
          ["an imperial", "a perfect", "an intense", "a brilliant"], "an intense"),
    298: ("The cleaning staff work ____, when the offices are empty.",
          ["from night", "in night", "on night", "at night"], "at night"),
    299: ("Several firms ____ to control the local delivery market.",
          ["placed", "struggled", "brought", "recognized"], "struggled"),
}

PART4 = {
    301: ("The client was not ____ the quality of the first shipment.",
          ["happy with", "happy for", "happy of", "happy at"], "happy with"),
    303: ("The director was ____ the results of the pilot project.",
          ["delighted to", "delighted of", "delighted with", "delighted in"], "delighted with"),
    304: ("The staff are ____ the launch of the new product line.",
          ["excited in", "excited on", "excited about", "excited with"], "excited about"),
    305: ("The supervisor was ____ delaying the report.",
          ["annoyed to me for", "annoyed with me at", "annoyed at me in", "annoyed with me for"], "annoyed with me for"),
    306: ("The new team leader has always been ____.",
          ["nice to me", "nice of me", "nice with me", "nice for me"], "nice to me"),
    307: ("It was ____ to send the invitation without checking the address.",
          ["stupid for me", "stupid to me", "stupid of me", "stupid by me"], "stupid of me"),
    308: ("The shareholders were ____ the size of the dividend.",
          ["surprised on", "surprised of", "surprised with", "surprised at"], "surprised at"),
    309: ("The client said she was ____ the presentation.",
          ["impressed about", "impressed for", "impressed with", "impressed in"], "impressed with"),
    310: ("We are ____ the delay in processing your claim.",
          ["sorry about", "sorry with", "sorry of", "sorry on"], "sorry about"),
    321: ("The board approved ____ plan to expand into Europe.",
          ["a five-year", "five-year", "the five-years", "a five-years"], "a five-year"),
    322: ("____ Asia-Pacific region accounts for half of our sales.",
          ["The", "A", "An", "-"], "The"),
    323: ("What ____ our clients expect!",
          ["high standards", "a high standards", "highs standards", "the high standard"], "high standards"),
    324: ("____ warehouse was quite empty last month.",
          ["This", "These", "This warehouses", "These warehouse"], "This"),
    325: ("We have ____ at eight before the factory tour.",
          ["some breakfast", "the breakfast", "a breakfast", "breakfast"], "breakfast"),
    326: ("The company lost many of ____ most experienced technicians in the restructuring.",
          ["its", "it's", "their", "hers"], "its"),
    327: ("One night there ____ a serious fire at the distribution centre.",
          ["is a serious fire", "has been a serious fire", "was a serious fire", "had been a serious fire"], "was a serious fire"),
    328: ("My brother works ____.",
          ["as an actor in our country", "as a conductor", "as a waiter in a local restaurant", "as a manager of our family business"], "as a manager of our family business"),
    329: ("A: 'Would you like some milk?' B: '____, please.'",
          ["A little", "Little", "A few", "Few"], "A little"),
    330: ("____ are sold in the hotel gift shop.",
          ["Kimono", "Kimonoes", "Kimonos", "Kimoni"], "Kimonos"),
    331: ("Do you have any ____ experience of this type of work?",
          ["contemporary", "instant", "modern", "previous"], "previous"),
    333: ("The team worked through lunch, so by three o'clock everyone was ____.",
          ["notable", "realistic", "famished", "conventional"], "famished"),
    335: ("Sorry to ____ you, but the client is waiting on line two.",
          ["disturb", "try", "expand", "accuse"], "disturb"),
    337: ("The strap on the sample bag is made of ____ leather.",
          ["nominal", "genuine", "loose", "anxious"], "genuine"),
    338: ("Full members enjoy special ____ such as free airport parking.",
          ["confidence", "principles", "privileges", "adventures"], "privileges"),
    339: ("The workers trapped in the mine were ____ by helicopter.",
          ["restricted", "restated", "rescued", "restored"], "rescued"),
    341: ("Listen to that conversation in the lobby. What language ____?",
          ["did they speak", "are they speaking", "do they speak", "have they spoken"], "are they speaking"),
    342: ("The magazine criticized the ____ images used in the advertising campaign.",
          ["sensuous", "sensitive", "sensational", "sensual"], "sensual"),
    344: ("She complained of her manager's inappropriate ____ towards the staff.",
          ["behavior", "mindset", "demand", "being"], "behavior"),
    345: ("Many candidates are ____ speaking in public.",
          ["terrified to", "terrified with", "terrified in", "terrified of"], "terrified of"),
    346: ("We have put your name on the waiting list and I do not ____ any problems.",
          ["certify", "appease", "foresee", "argue"], "foresee"),
    348: ("I did not see your car in the lot, so I ____ you had already left.",
          ["assumed", "forged", "trailed", "conditioned"], "assumed"),
    349: ("The chamber of commerce hosted ____ to welcome the new ambassador.",
          ["dinner", "a dinner", "the dinner", "dinners"], "a dinner"),
    350: ("____ division posted the strongest growth this quarter.",
          ["The European", "A European", "An European", "European"], "The European"),
    351: ("The cafeteria ordered five ____ of bread for the breakfast service.",
          ["loafs", "loves", "loaves", "loaf"], "loaves"),
    352: ("The training video was ____, so most participants lost interest.",
          ["bored", "bore", "boring", "bores"], "boring"),
    353: ("The store introduced a ____ return policy for online purchases.",
          ["30 day", "30-day", "30-days", "30 day's"], "30-day"),
    354: ("The technician asked for ____.",
          ["a knife long and sharp", "a knife sharp and long", "a sharp long knife", "a long sharp knife"], "a long sharp knife"),
    355: ("The new depot is ____ from the port than the old one.",
          ["far", "farther", "furthest", "farthest"], "farther"),
    357: ("This is the most efficient system that ____.",
          ["we have ever installed", "we ever installed", "we ever install", "we have ever installing"], "we have ever installed"),
    358: ("A: 'Do you want a larger office?' B: 'Yes, ____.'",
          ["the big the good", "the bigger the better", "the biggest the best", "the bigger better"], "the bigger the better"),
    359: ("Our team earns less than ____.",
          ["him", "he does", "his", "he is"], "he does"),
    360: ("The new lifts are designed for ____.",
          ["a disable", "the disable", "a disabled", "the disabled"], "the disabled"),
    364: ("Neither of the two proposals ____ the requirements of the tender.",
          ["meets", "meet", "are meeting", "have met"], "meets"),
    368: ("Hardly ____ the announcement when the employees started applauding.",
          ["had the CEO made", "the CEO had made", "the CEO made", "did the CEO make"], "had the CEO made"),
    371: ("Visitors must ____ their shoes off before entering the clean room.",
          ["call", "put", "take", "do"], "take"),
    372: ("Ms. Renault ____ Lyon, so she is used to long commutes.",
          ["comes from", "comes in", "comes to", "comes on"], "comes from"),
    374: ("The candidate was supposed to come for an interview, but she has not ____ yet.",
          ["shown out", "shown in", "shown by", "shown up"], "shown up"),
    375: ("The seminar was so dull that two participants ____.",
          ["dozed out", "dozed off", "dozed away", "dozed by"], "dozed off"),
    377: ("The supplier kept refusing to lower the price, but finally ____.",
          ["gave off", "gave away", "gave for", "gave in"], "gave in"),
    379: ("The doctor did not think the patient's chances were good, but he ____.",
          ["pulled in", "pulled through", "pulled out", "pulled on"], "pulled through"),
    380: ("You may use the lounge, but please ____ the Persian rug.",
          ["staff off", "stay by", "stay in", "stay off"], "stay off"),
    383: ("The newsletter summarizes all ____ developments in the industry.",
          ["recent", "interpretative", "natural", "intelligent"], "recent"),
    384: ("The new budget rules have ____ the travel allowances of senior staff.",
          ["serviced", "based", "informed", "curtailed"], "curtailed"),
    389: ("The region has ____ deposits of lithium, which attracted several battery makers.",
          ["abundant", "long", "progressive", "geographic"], "abundant"),
    390: ("The company started as a ____ of a larger American group before it became independent.",
          ["capital", "colony", "population", "inhabitants"], "colony"),
    391: ("____ is known about the side effects of the new drug.",
          ["Few", "A few", "Little", "A little"], "Little"),
    392: ("____ looks calm today, so the ferry should run on time.",
          ["Sea", "A sea", "An sea", "The sea"], "The sea"),
    394: ("The journey was ____, so the team went straight to the hotel.",
          ["tiring", "tired", "tires", "tire"], "tiring"),
    395: ("We rented a small office ____ the lake.",
          ["above", "over", "up", "in"], "above"),
    398: ("Everyone in the department ____ required to attend the briefing.",
          ["am", "is", "are", "were"], "is"),
    399: ("A: 'Where is Mr. Wells?' B: 'He ____ after his flight.'",
          ["has a shower", "had a shower", "has had a shower", "is having a shower"], "is having a shower"),
}

REST.update(PART3)
REST.update(PART4)

PART5 = {
    401: ("Do not enter the laboratory. The engineers ____ a test on the new motor.",
          ["doesn't run", "isn't running", "hasn't run", "aren't running"], "aren't running"),
    402: ("The staff are all ____ the merger with the rival firm.",
          ["of", "for", "about", "with"], "about"),
    404: ("The Netherlands is ____ in the European Union.",
          ["a EU country", "an EU country", "the EU country", "EU country"], "an EU country"),
    405: ("She ____ a hard hat before entering the construction site.",
          ["put on", "put in", "put into", "put onto"], "put on"),
    406: ("The conveyor belt must be ____ before the safety guard is removed.",
          ["stationary", "stationery", "static", "statistical"], "stationary"),
    407: ("The loss from the fire is ____ to be at least two million dollars.",
          ["comforted", "attested", "rated", "estimated"], "estimated"),
    409: ("The new catalogue ____ customers a wider range of office furniture.",
          ["offers", "offer", "offering", "is offered"], "offers"),
    414: ("The manager showed ____ interest in the proposal and rejected it.",
          ["few", "a few", "little", "a little"], "little"),
    416: ("____ in the new conference room is very bright.",
          ["The light", "Light", "A light", "Lights"], "The light"),
    419: ("The CEO ____ that the company had no plans to move its headquarters.",
          ["endowed", "waked", "escaped", "asserted"], "asserted"),
    420: ("The candidate has a ____ degree in economics from Seoul National University.",
          ["bachelor", "bachelor's", "bachelors", "bachelorship"], "bachelor's"),
    421: ("The conference host gave each speaker a ____ of local flowers.",
          ["twig", "bouquet", "compilation", "pack"], "bouquet"),
    423: ("In the race for the chairmanship, Ms. Fischer was Mr. Duval's leading ____.",
          ["opponent", "auxiliary", "convict", "vanity"], "opponent"),
    426: ("The auditors described the state of the accounts as ____.",
          ["shock", "shocks", "shocked", "shocking"], "shocking"),
    427: ("The company's wellness programme offers a range of ____, from yoga to hiking.",
          ["recreations", "expansions", "enmities", "sympathies"], "recreations"),
    429: ("What ____ the auditors is why the invoices are dated next year.",
          ["puzzles", "tests", "searches", "weighs"], "puzzles"),
    431: ("The warranty on the new machines ____ for three years.",
          ["expands", "increases", "extends", "enlarges"], "extends"),
    432: ("I cannot ____ why the system keeps rejecting valid orders.",
          ["figure out", "figure over", "figure off", "figure with"], "figure out"),
    433: ("Please turn off your phone so as not to ____ the other candidates.",
          ["dispense", "engross", "absorb", "distract"], "distract"),
    434: ("Can I borrow your stapler? I will ____ after the meeting.",
          ["give it back", "give it out", "give it away", "give it in"], "give it back"),
    436: ("The factory has been ____ extra staff to meet the Christmas demand.",
          ["putting off", "putting out", "putting in", "putting on"], "putting on"),
    437: ("The new regulations ____ the pressure on small exporters.",
          ["slandered", "intensified", "topped", "ravaged"], "intensified"),
    438: ("Do not ____ the packing slip before the order has been checked.",
          ["throw off", "throw away", "throw out", "throw up"], "throw away"),
    439: ("The machine's ____ performance has worried the maintenance team.",
          ["devious", "erratic", "mischievous", "crooked"], "erratic"),
    440: ("I am sorry to postpone, but I do not ____ attending the dinner tonight.",
          ["feel up to", "feel up with", "feel up on", "feel up in"], "feel up to"),
    442: ("The sales manager usually ____ on business trips at weekends.",
          ["go away", "goes away", "is going away", "has gone away"], "goes away"),
    443: ("Why are you always so ____ your colleagues' success?",
          ["jealous in", "jealous about", "jealous with", "jealous of"], "jealous of"),
    446: ("The worker suffered minor cuts and ____ when the pallet fell.",
          ["openings", "slits", "forms", "bruises"], "bruises"),
    449: ("You have to be ____ 18 to work night shifts in this plant.",
          ["over", "above", "up", "more"], "over"),
    450: ("The supplier ____ to deliver the goods by Friday.",
          ["agreed", "accepted", "inclined", "seemed"], "agreed"),
    452: ("The river is too ____ here for heavy barges.",
          ["insane", "damned", "capable", "shallow"], "shallow"),
    453: ("Ms. Ito will be the ____ at the product launch.",
          ["presenter", "a presenter", "an presenter", "presenters"], "presenter"),
    454: ("Mr. Hall ____ a family of shopkeepers and now runs his own chain.",
          ["came to", "came by", "came from", "came in"], "came from"),
    457: ("The auditors checked all the ledgers, ____?",
          ["didn't they", "wasn't they", "hadn't they", "wouldn't they"], "didn't they"),
    458: ("What is all that noise in the corridor? What ____?",
          ["has gone on", "went on", "goes on", "is going on"], "is going on"),
    459: ("Ms. Yates is very ____ the confusion caused by the invoice.",
          ["sorry for", "sorry in", "sorry with", "sorry by"], "sorry for"),
    461: ("The staff ____ to finish the presentation before the client arrived.",
          ["dated", "rushed", "wooed", "bullied"], "rushed"),
    462: ("The company ____ donations to the local school every year.",
          ["is giving", "gave", "has given", "gives"], "gives"),
    463: ("The board was ____ the sudden rise in the supplier's prices.",
          ["suspicious of", "suspicious with", "suspicious for", "suspicious by"], "suspicious of"),
    464: ("The chef received glowing ____ on the banquet he prepared for the guests.",
          ["compliments", "complements", "completion", "completeness"], "compliments"),
    466: ("She ____ the table before the meeting started.",
          ["took the papers away", "took the papers out", "took the papers off", "took the papers over"], "took the papers off"),
    467: ("Here is ____ wrapping paper for the samples.",
          ["a bit of", "bit of", "a bits", "a bit"], "a bit of"),
    468: ("Sales ____ sharply in the first winter after the launch.",
          ["fell", "felt", "falls", "was falling"], "fell"),
    469: ("The research station lies five degrees north of ____.",
          ["equator", "a equator", "an equator", "the equator"], "the equator"),
    470: ("Leaving the fruit in the heat will ____ it within a day.",
          ["quarrel", "defile", "permit", "rot"], "rot"),
    472: ("The commission described the treatment of the workers as nothing short of ____.",
          ["barbaric", "well-bred", "peeled", "exhausted"], "barbaric"),
    474: ("____ should all complete the safety training before Friday.",
          ["Ours", "We're", "Us", "We"], "We"),
    475: ("I ____ a very useful book on negotiation at the moment.",
          ["read", "am reading", "have read", "been reading"], "am reading"),
    476: ("The team is ____ meeting the deadline if extra staff are hired.",
          ["capable of", "capable with", "capable on", "capable in"], "capable of"),
    477: ("The guests are waiting in ____ of the restaurant.",
          ["a garden", "an garden", "the garden", "garden"], "the garden"),
    480: ("The crane lifted the container ____ the fence.",
          ["over", "across", "along", "into"], "over"),
    491: ("The sales ____ for the next quarter looks encouraging.",
          ["forecast", "foreword", "forefather", "forehead"], "forecast"),
    494: ("His ____ knowledge of the local market made the board doubt his competence.",
          ["inadequate", "invaluable", "inevitable", "inordinate"], "inadequate"),
    497: ("It is high time we ____ the outdated booking system.",
          ["replace", "replaced", "have replaced", "will replace"], "replaced"),
    498: ("No sooner had the meeting begun ____ the fire alarm went off.",
          ["when", "that", "than", "then"], "than"),
    499: ("She is used to ____ up early for the weekly conference call.",
          ["get", "got", "getting", "have got"], "getting"),
    500: ("The interns are looking forward to ____ a day at the design studio.",
          ["spend", "spending", "have spent", "spent"], "spending"),
}

PART7 = {
    632: ("The shipment was delayed, ____ the client was informed immediately.",
          ["and", "because", "so", "as"], "so"),
    642: ("Mr. Doyle and Ms. Reyes will give ____ presentation tomorrow.",
          ["his", "its", "their", "theirselves"], "their"),
    646: ("All dishes in the hotel restaurant are seasoned to ____.",
          ["prediction", "perfection", "perdition", "permission"], "perfection"),
    647: ("Would you mind ____ me the file before the meeting?",
          ["to bring", "bringing", "brought", "brings"], "bringing"),
    648: ("The company's long-standing partnership with the supplier will ____ come to an end this year.",
          ["totally", "very", "temporarily", "finally"], "finally"),
    660: ("Have you ever ____ to the Frankfurt trade fair?",
          ["gone", "come", "been", "went"], "been"),
    664: ("I ____ when the courier arrived with the documents.",
          ["was sleeping", "had been sleeping", "slept", "sleep"], "was sleeping"),
    667: ("The estimate for the office painting will be ready in a ____ more days.",
          ["little", "few", "several", "short"], "few"),
    671: ("The new wing of the hospital was named ____ the company's founder.",
          ["beside", "after", "over", "before"], "after"),
    673: ("Are you ready ____ the new equipment now?",
          ["ordering", "orders", "to order", "ordered"], "to order"),
    674: ("Could I have tea ____ coffee at the briefing?",
          ["rather for", "prefer to", "better than", "instead of"], "instead of"),
}

PART8 = {
    705: ("Please ____ the temperature of the cold store every four hours.",
          ["monitoring", "monitored", "monitors", "monitor"], "monitor"),
    733: ("After ____ the two suppliers' quotes, she made her decision easily.",
          ["looking", "side-by-side", "advertising", "comparing"], "comparing"),
    765: ("That trade fair was the ____ event of the year.",
          ["funnest", "funniest", "enjoyable", "most enjoyable"], "most enjoyable"),
    767: ("The ____ rise in fuel costs caught the industry by surprise.",
          ["gradual", "typical", "sudden", "minor"], "sudden"),
    774: ("That photograph was ____ at the opening of the new branch.",
          ["took", "taken", "taking", "takes"], "taken"),
    776: ("They were equally qualified, but Mr. Yoon just ____ Ms. Park out for the post.",
          ["handed", "kneed", "eyed", "nosed"], "nosed"),
}

PART9 = {
    801: ("The new warehouse is ____ to the main plant.",
          ["adjacent from", "adjacent with", "adjacent by", "adjacent to"], "adjacent to"),
    802: ("Are you ____ attending the industry conference in Busan?",
          ["interested in", "interested of", "interested by", "interested on"], "interested in"),
    804: ("The receptionist was ____ the visitors, so the manager apologized.",
          ["unfriendly to", "unfriendly at", "unfriendly on", "unfriendly in"], "unfriendly to"),
    805: ("We are ____ the mistake in your invoice and will issue a credit note.",
          ["sorry in", "sorry on", "sorry to", "sorry for"], "sorry for"),
    806: ("The staff were not ____ the change in the delivery schedule.",
          ["aware to", "aware of", "aware for", "aware on"], "aware of"),
    808: ("The factory is heavily ____ a single supplier of microchips.",
          ["dependent with", "dependent on", "dependent by", "dependent to"], "dependent on"),
    810: ("Who was ____ the delay in the shipment?",
          ["responsible for", "responsible in", "responsible on", "responsible by"], "responsible for"),
    811: ("The new manager will take up her post ____ a week.",
          ["on", "by", "in", "to"], "in"),
    813: ("The interview is scheduled ____ Friday morning.",
          ["to", "in", "on", "at"], "on"),
    814: ("The train to the trade fair will be leaving ____ a few minutes.",
          ["on", "in", "at", "by"], "in"),
    815: ("The office is closed ____ Christmas.",
          ["in", "at", "by", "on"], "at"),
    816: ("Do you work ____ the evenings?",
          ["by", "at", "on", "in"], "in"),
    817: ("The new plant will be operational ____ six months' time.",
          ["at", "on", "by", "in"], "in"),
    818: ("Mr. Feld and I arrived ____ the same time.",
          ["in", "on", "at", "by"], "at"),
    819: ("Will you be in the office ____ the weekend?",
          ["at", "in", "to", "on"], "at"),
    820: ("The courier will deliver the samples ____ the morning.",
          ["by", "at", "on", "in"], "in"),
    821: ("The consultant ____ we were referring to has left the company.",
          ["who", "whom", "who's", "whose"], "whom"),
    822: ("Do you know ____ won the contract for the new terminal?",
          ["who", "whom", "who's", "whose"], "who"),
    823: ("I wonder ____ the committee recommended as the next chairman.",
          ["who's", "who", "whose", "whom"], "whom"),
    825: ("I am pretty sure ____ the new supervisor is.",
          ["who's", "whose", "whom", "who"], "who"),
    826: ("Mr. Ellis is the accountant ____ everybody trusts.",
          ["whom", "who", "who's", "whose"], "whom"),
    827: ("He is the manager ____ I would like to work with.",
          ["who", "whose", "whom", "who's"], "whom"),
    828: ("____ do you think drafted the new safety policy?",
          ["Who's", "Whose", "Whom", "Who"], "Who"),
    829: ("The bonus will be given to ____ deserves it most.",
          ["whomever", "whoever", "whosoever", "whatever"], "whoever"),
    830: ("Do you know ____ the new sales representatives are?",
          ["whom", "whose", "who", "who's"], "who"),
    834: ("It was ____ who authorized the payment.",
          ["me", "I", "my", "I'm"], "I"),
    835: ("Two of our engineers, ____, will attend the conference in Berlin.",
          ["him and me", "his and mine", "he and I", "he's and I'm"], "he and I"),
    836: ("____ managers must complete the compliance course by June.",
          ["We", "Us", "Ours", "We're"], "We"),
    837: ("The top performers this quarter are Ms. Nam and ____.",
          ["mine", "me", "I", "I'm"], "I"),
    838: ("The director summoned the two auditors and ____.",
          ["mine", "my", "I", "me"], "me"),
    840: ("The chef served the guests and ____ a six-course dinner.",
          ["me", "I", "my", "mine"], "me"),
    844: ("The average ____ of the equipment is five years, according to the manufacturer.",
          ["life span", "life-span", "lifetime", "live span"], "life span"),
}

REST.update(PART5)
REST.update(PART7)
REST.update(PART8)
REST.update(PART9)

# second look: items whose options allowed more than one defensible answer
FIXUPS2 = {
    202: ("Ms. Ferris ____ by the IT team at the new branch office yesterday.",
          ["had her laptop repaired", "repaired her laptop", "was repaired her laptop", "has her laptop repaired"], "had her laptop repaired"),
    305: ("The supervisor was ____ me for delaying the report.",
          ["annoyed to me for", "annoyed with me at", "annoyed at me in", "annoyed with me for"], "annoyed with me for"),
    325: ("The technicians went back to ____ after the alarm was cancelled.",
          ["the work", "a work", "work", "works"], "work"),
    328: ("My brother is a ____ of our family business.",
          ["manager", "manage", "management", "managing"], "manager"),
}
REST.update(FIXUPS2)

# third wave: the remaining general-knowledge / personal-life items
PART_REST2 = {
    27: ("Without the new software, the audit team could ____ have finished on time.",
         ["no", "never", "ever", "sometimes"], "never"),
    48: ("The company moved ____ its new headquarters on the 3rd of last month.",
         ["at", "into", "over", "through"], "into"),
    99: ("The investors showed complete ____ in the new management team.",
         ["confident", "competent", "confidence", "confidential"], "confidence"),
    115: ("Some employees feel they must always disagree ____ their supervisors.",
          ["against", "about", "to", "with"], "with"),
    118: ("Receiving clear instructions ____ the new intern feel more confident at the counter.",
          ["forced", "made", "help", "has"], "made"),
    154: ("In their ____ to cut costs, managers ignored the impact on staff morale.",
          ["harmony", "zeal", "accord", "alleviation"], "zeal"),
    164: ("The support team receives complaints all day, but they never argue. They just ____.",
          ["feel up to it", "get over with it", "go along with it", "put up with it"], "put up with it"),
    234: ("Employees are ____ to suggest improvements to the safety procedures.",
          ["intimidated", "feared", "challenged", "bored"], "challenged"),
    235: ("Have you ever ____ how much the new booking system has cut waiting times?",
          ["dreamed", "realized", "seen", "theorized"], "realized"),
    238: ("Goods are packed at the warehouse and then ____ to the retail outlets.",
          ["mailed", "ferried", "airlifted", "transported"], "transported"),
    251: ("The report examines the time ____ the company first entered the Asian market.",
          ["on how", "when", "where", "why"], "when"),
    255: ("Our new stores do not attract many tourists, ____?",
          ["do they", "don't they", "aren't they", "are they"], "do they"),
    261: ("Did you receive an ____ the supplier's annual dinner?",
          ["invitation to", "invitation for", "invitation with", "invitation on"], "invitation to"),
    277: ("I asked my supervisor for ____ about the new expense policy.",
          ["discussion", "companion", "facilitation", "clarification"], "clarification"),
    302: ("Several staff members are ____ the change in shift patterns.",
          ["upset with", "upset about", "upset for", "upset to"], "upset about"),
    329: ("A: 'Would you like some coffee?' B: '____, please.'",
          ["Few", "A little", "Little", "A few"], "A little"),
    373: ("The delivery van was driving too fast and ____ a lamp post.",
          ["ran in", "ran off", "ran on", "ran into"], "ran into"),
    381: ("After the failed merger, a fresh ____ was made to enter the European market.",
          ["birth", "expression", "attempt", "system"], "attempt"),
    382: ("From the time that the agency was ____, many smaller firms have joined as partners.",
          ["fulfilled", "stated", "pledged", "founded"], "founded"),
    385: ("The corporation's ____ resources allowed it to lead in research and development.",
          ["divided", "continuous", "immense", "different"], "immense"),
    386: ("The first satellite ____ by the agency was placed in orbit in 2019.",
          ["orbited", "boarded", "returned", "launched"], "launched"),
    387: ("Most of our revenue ____ from the activities of the European branch.",
          ["generates", "inspires", "desires", "suppresses"], "generates"),
    410: ("I wish I ____ the manager, so I could approve the budget myself.",
          ["was", "were", "am", "have"], "were"),
    413: ("The trainee felt ____, shy and awkward at her first client meeting.",
          ["clumsy", "attracted", "versatile", "sincere"], "clumsy"),
    417: ("The inspectors found workers standing on ____ floors without safety boots.",
          ["simple", "bare", "somber", "light"], "bare"),
    441: ("( at the conference ) Hello, Jane. ____ the conference?",
          ["Do you enjoy", "Are you enjoying", "Have you enjoy", "Did you enjoy"], "Are you enjoying"),
    444: ("Our team is not very ____ repairing the older machines.",
          ["good in", "good about", "good at", "good with"], "good at"),
    451: ("It is ____ that customers should pay such high delivery charges.",
          ["outrageous", "opaque", "evasive", "genteel"], "outrageous"),
    470: ("Leaving the produce in the heat will ____ it within a day.",
          ["permit", "rot", "quarrel", "defile"], "rot"),
    615: ("____ heavy rain, this afternoon's site inspection has been rescheduled for Friday.",
          ["Due to", "Because", "As", "Despite"], "Due to"),
    623: ("Our logistics partner is more reliable than its rivals, because its drivers have better training and are more ____.",
          ["experience", "experiencing", "experiential", "experienced"], "experienced"),
    633: ("Ms. Balfour is a talented accountant, but corporate tax law is her ____.",
          ["specialties", "special", "specialty", "specializes"], "specialty"),
    689: ("Because the factory runs three shifts, it can experience a wide ____ of demand in any 24-hour period.",
          ["type", "varieties", "distinctness", "range"], "range"),
    704: ("The counselor noted that shift workers must be ____ in regard to working hours and conditions.",
          ["flexible", "flexibility", "flexibly", "flexibleness"], "flexible"),
    717: ("Please choose ____ the following delivery options: standard, express, same-day, or pickup.",
          ["between", "among", "along", "either of"], "among"),
    718: ("The sales ____ for the coming quarter calls for modest growth in the retail division.",
          ["reporter", "condition", "predilection", "forecast"], "forecast"),
    763: ("I ____ updating the client database a lot recently.",
          ["am to be", "was being", "have been", "was to be"], "have been"),
    769: ("The services offered by the agency ____ from basic bookkeeping to full audits.",
          ["range", "ranges", "ranging", "will range"], "range"),
    788: ("Prices were reported to be ____ to 20 percent higher than last year.",
          ["up", "of", "out", "in"], "up"),
    824: ("Ms. Hall is the analyst ____ I believe commands the respect of the whole department.",
          ["who", "whom", "whose", "who's"], "whom"),
    831: ("____ finally granted the employees' request for flexible hours.",
          ["Ours", "Us", "We're", "We"], "We"),
    832: ("____ and her assistant are planning the product launch.",
          ["She", "Her", "She's", "Hers"], "She"),
    839: ("The director invited the auditors and ____ to the briefing.",
          ["our", "ours", "us", "we"], "us"),
    845: ("Construction and mining are dangerous industries that have a lot of occupational ____.",
          ["risks", "dangers", "problems", "hazards"], "hazards"),
}
REST.update(PART_REST2)
