# -*- coding: utf-8 -*-
"""
rebuild_items.py — the replacement questions for toeic_web_app/rebuild_bank.py.

Every entry is a TOEIC-style incomplete sentence set in a workplace/business
context, with four options and exactly one defensible answer. These rows replace
the dictionary-definition items, the "Which sentence is correct ?" drills, the
duplicates and the items whose options were mangled (see BANK_AUDIT.md).

Format:  id: (sentence with ____, [four options], correct option)
"""

# --- bank part 6 ("Grammar Part 4"): was a dictionary quiz -------------------
P6 = {
    501: ("The company will ____ its new product line at the international trade fair in May.",
          ["unveil", "unfold", "unload", "unwind"], "unveil"),
    502: ("Employees who wish to ____ their working hours must speak with their supervisor.",
          ["adjust", "adopt", "adore", "advise"], "adjust"),
    503: ("The supplier promised to ____ the order within three business days.",
          ["deliver", "decide", "declare", "defend"], "deliver"),
    504: ("Please ____ the attached form and return it to the human resources department.",
          ["complete", "compete", "compute", "complain"], "complete"),
    505: ("The receptionist will ____ visitors at the front desk and give them a temporary badge.",
          ["greet", "grate", "grasp", "grind"], "greet"),
    506: ("The accounting department is responsible for the ____ of all expense reports.",
          ["review", "reviewer", "revelation", "reversal"], "review"),
    507: ("Management decided to ____ the annual conference because of the new travel restrictions.",
          ["cancel", "connect", "consult", "convert"], "cancel"),
    508: ("The warranty does not ____ damage caused by improper use of the equipment.",
          ["cover", "carve", "cater", "cease"], "cover"),
    509: ("All job ____ must be submitted through the company website.",
          ["applications", "appliances", "appointments", "appraisals"], "applications"),
    510: ("The finance team will ____ the budget for the next fiscal year.",
          ["prepare", "prevent", "preserve", "presume"], "prepare"),
    511: ("Full-time employees are entitled to a range of ____, including health insurance and paid vacation.",
          ["benefits", "beneficiaries", "policies", "incomes"], "benefits"),
    512: ("The sales team exceeded its ____ for the third quarter by almost ten percent.",
          ["target", "ticket", "talent", "task"], "target"),
    513: ("Please ____ the invoice before sending it back to the vendor.",
          ["approve", "approach", "apply", "appoint"], "approve"),
    514: ("The airline agreed to ____ passengers for the long delay.",
          ["compensate", "compete", "compile", "complain"], "compensate"),
    515: ("The new employee was asked to ____ the safety guidelines before starting work.",
          ["review", "reserve", "reveal", "reverse"], "review"),
    516: ("The factory will ____ production until the new safety system is installed.",
          ["suspend", "supply", "support", "suppose"], "suspend"),
    517: ("Customers may ____ their purchase within 30 days for a full refund.",
          ["return", "relate", "remain", "repair"], "return"),
    518: ("The manager asked the team to ____ the report before the client meeting.",
          ["finalize", "finance", "furnish", "facilitate"], "finalize"),
    519: ("The company will ____ the old office equipment with more efficient models.",
          ["replace", "replay", "reply", "repel"], "replace"),
    522: ("The quarterly ____ showed a steady increase in online sales.",
          ["figures", "features", "futures", "fixtures"], "figures"),
    523: ("Please keep your ____ in a safe place, as the tickets cannot be reissued.",
          ["receipt", "recipe", "recipient", "reception"], "receipt"),
    524: ("The marketing team will ____ the results of the survey at next week's meeting.",
          ["present", "preserve", "prevent", "pretend"], "present"),
    525: ("The company has decided to ____ the deadline by two weeks.",
          ["extend", "expand", "expend", "expose"], "extend"),
    526: ("Passengers are advised to ____ at the airport two hours before departure.",
          ["arrive", "arrange", "arise", "arouse"], "arrive"),
    527: ("The new branch office will ____ next month in the city centre.",
          ["open", "offer", "order", "obey"], "open"),
    528: ("The supervisor ____ the trainees on how to operate the new machine.",
          ["instructed", "insisted", "installed", "invested"], "instructed"),
    529: ("Our supplier has ____ the delivery date twice this month.",
          ["postponed", "proposed", "promoted", "prohibited"], "postponed"),
    530: ("The customer asked for a ____ on the final price.",
          ["discount", "disclosure", "discourse", "disaster"], "discount"),
    531: ("The personnel department will ____ the applications next week.",
          ["evaluate", "evacuate", "evaporate", "evade"], "evaluate"),
    532: ("The company plans to ____ its operations into the Southeast Asian market.",
          ["expand", "expend", "expire", "expel"], "expand"),
    533: ("The client was ____ with the quality of the sample products.",
          ["satisfied", "satisfying", "satisfaction", "satisfy"], "satisfied"),
    534: ("The auditor asked the staff to ____ all the receipts for the last quarter.",
          ["retain", "retire", "retreat", "return"], "retain"),
    535: ("Ms. Watanabe was ____ of the change in the delivery schedule.",
          ["notified", "noticing", "noticeable", "notion"], "notified"),
    536: ("The warehouse manager keeps a careful ____ of all incoming goods.",
          ["record", "recorder", "recording", "recorded"], "record"),
    537: ("The firm's ____ of the local market helped it win the contract.",
          ["knowledge", "knowledgeable", "knowingly", "known"], "knowledge"),
    538: ("The new system will ____ the time needed to process each claim.",
          ["reduce", "deduce", "induce", "produce"], "reduce"),
    539: ("The manager offered the team a ____ on how to handle difficult clients.",
          ["workshop", "worksheet", "workload", "workflow"], "workshop"),
    540: ("All employees are asked to ____ the new safety rules by next Monday.",
          ["comply with", "comply to", "comply for", "comply in"], "comply with"),
    541: ("The accountant found a small ____ in the monthly statement.",
          ["discrepancy", "discretion", "discovery", "discussion"], "discrepancy"),
    542: ("The airline will ____ the tickets to the travel agent tomorrow.",
          ["issue", "issuing", "issuance", "issued"], "issue"),
    543: ("The plant's ____ has increased since the robots were installed.",
          ["output", "outcome", "outlet", "outlook"], "output"),
    544: ("The firm offers a ____ bonus to employees who stay for five years.",
          ["retention", "retentioned", "retentive", "retaining"], "retention"),
    545: ("Please ____ your password if you cannot access the customer database.",
          ["reset", "resit", "resettle", "restate"], "reset"),
    546: ("The director will ____ the progress of the project every Monday.",
          ["oversee", "overlook", "overcome", "overtake"], "oversee"),
    547: ("The company's new policy takes ____ on 1 September.",
          ["effect", "affect", "effort", "effective"], "effect"),
    548: ("Customers who return the item will receive a full ____.",
          ["refund", "refusal", "refinery", "refuge"], "refund"),
    549: ("The sales representative will ____ the order to the regional office.",
          ["forward", "forwarded", "forwarding", "forwards"], "forward"),
    550: ("The committee reviewed the ____ of the previous meeting.",
          ["minutes", "minute", "minuteness", "minutiae"], "minutes"),
    551: ("The manager will ____ the new intern with the payroll system.",
          ["familiarize", "familiarity", "familiar", "familiarly"], "familiarize"),
    552: ("The company's annual report will be ____ to all shareholders.",
          ["distributed", "distributing", "distribution", "distribute"], "distributed"),
    553: ("The clinic's new ____ equipment was installed last week.",
          ["therapeutic", "therapy", "therapist", "therapies"], "therapeutic"),
    554: ("Management expects a ____ improvement in sales next quarter.",
          ["positive", "positively", "position", "positioned"], "positive"),
    555: ("The team leader offered ____ to the staff after the difficult week.",
          ["encouragement", "encouraged", "encouraging", "encourage"], "encouragement"),
    556: ("The hotel manager apologized for the ____ in the reservation system.",
          ["error", "era", "erase", "erroneous"], "error"),
    557: ("The board will ____ the annual budget at its next meeting.",
          ["approve", "approval", "approved", "approving"], "approve"),
    558: ("All visitors must ____ at the security desk before entering the plant.",
          ["register", "registration", "registered", "registrar"], "register"),
    559: ("The company has been ____ with the same law firm for over a decade.",
          ["working", "work", "worked", "works"], "working"),
    560: ("The new marketing strategy proved highly ____ in the first month.",
          ["effective", "effect", "effectively", "effectiveness"], "effective"),
    561: ("The director asked for a ____ of the latest sales figures.",
          ["summary", "summarize", "summarized", "summarily"], "summary"),
    562: ("The shipping department will ____ the goods by air freight.",
          ["transport", "transportation", "transported", "transporter"], "transport"),
    563: ("The staff meeting was ____ to Tuesday because of the holiday.",
          ["rescheduled", "rescheduling", "reschedule", "reschedules"], "rescheduled"),
    564: ("The company offers free ____ to all new employees.",
          ["orientation", "orient", "oriented", "oriental"], "orientation"),
    565: ("The consultant will ____ the findings of the survey to the board.",
          ["summarize", "summary", "summarized", "summarily"], "summarize"),
    566: ("The airline offers a ____ meal on all long-haul flights.",
          ["complimentary", "complementary", "compliment", "complimented"], "complimentary"),
    567: ("The company's ____ of the defective parts was praised by the inspectors.",
          ["disposal", "dispose", "disposed", "disposable"], "disposal"),
    568: ("The gallery will ____ works by local artists next month.",
          ["exhibit", "exhibition", "exhibited", "exhibiting"], "exhibit"),
    569: ("The firm ____ its first overseas office twenty years ago.",
          ["established", "establish", "establishment", "establishing"], "established"),
    570: ("The technician will ____ the printer before the office reopens.",
          ["repair", "repaired", "repairing", "reparation"], "repair"),
    571: ("The new contract is ____ to both parties under the current terms.",
          ["favourable", "favour", "favourably", "favourite"], "favourable"),
    572: ("The company was ____ for its excellent customer service.",
          ["recognized", "recognition", "recognizing", "recognizable"], "recognized"),
    573: ("The warehouse is fully ____ with automated sorting equipment.",
          ["equipped", "equipment", "equipping", "equip"], "equipped"),
    574: ("The manager's ____ to the proposal was obvious from her tone.",
          ["objection", "object", "objected", "objectively"], "objection"),
    575: ("The airline will ____ boarding thirty minutes before departure.",
          ["commence", "commencement", "commenced", "commencing"], "commence"),
    576: ("The report ____ three possible locations for the new plant.",
          ["identifies", "identification", "identical", "identically"], "identifies"),
    577: ("The supervisor praised the staff for their ____ to the project.",
          ["contribution", "contribute", "contributing", "contributor"], "contribution"),
    578: ("All equipment must be ____ before it leaves the factory.",
          ["inspected", "inspection", "inspector", "inspect"], "inspected"),
    579: ("The company's profits are expected to ____ next year.",
          ["increase", "increasing", "increased", "increasingly"], "increase"),
    580: ("The buyer asked for a ____ of the delivery schedule in writing.",
          ["confirmation", "confirm", "confirmed", "confirming"], "confirmation"),
    581: ("The documents were ____ by the legal department yesterday.",
          ["authenticated", "authentication", "authentic", "authentically"], "authenticated"),
    582: ("The growing demand for plant-based products ____ the market rapidly.",
          ["is changing", "change", "have changed", "were changing"], "is changing"),
    583: ("The director refused to ____ the details of the pending deal.",
          ["disclose", "disclosure", "disclosed", "disclosing"], "disclose"),
    584: ("The hotel has ____ its room rates for the holiday season.",
          ["reduced", "reduction", "reducing", "reduce"], "reduced"),
    585: ("The new employees received a thorough ____ of the safety rules.",
          ["explanation", "explain", "explained", "explaining"], "explanation"),
    586: ("The company is seeking ____ for the vacant regional manager post.",
          ["candidates", "candidacy", "candidly", "candidate"], "candidates"),
    587: ("The shipment arrived ____ despite the severe weather conditions.",
          ["safely", "safe", "safety", "safeness"], "safely"),
    588: ("The board will ____ the quarterly results with the shareholders tomorrow.",
          ["discuss", "discussion", "discussed", "discussing"], "discuss"),
    589: ("The audit revealed that all transactions were properly ____.",
          ["recorded", "record", "recording", "recorder"], "recorded")
}

# --- bank parts 1, 3, 4, 5: dictionary items and "Which sentence is correct ?"
GRAMMAR = {
    1: ("The consultant's report was praised for its ____ analysis of the market.",
        ["insightful", "insight", "insightfully", "insights"], "insightful"),
    481: ("The ____ of the new advertising campaign will be measured next quarter.",
          ["effectiveness", "effective", "effectively", "effects"], "effectiveness"),
    482: ("The designer used a chart to ____ the sales trend for the board.",
          ["depict", "depicts", "depiction", "depicting"], "depict"),
    483: ("Television remains an important ____ for reaching older customers.",
          ["medium", "media", "median", "medley"], "medium"),
    484: ("The publisher holds the ____ to all articles printed in the magazine.",
          ["copyright", "copywriter", "copyrighted", "copying"], "copyright"),
    485: ("The chairman's ____ donation funded the new research laboratory.",
          ["magnanimous", "magnanimity", "magnanimously", "magnate"], "magnanimous"),
    486: ("The city invested heavily in ____ such as roads and power lines.",
          ["infrastructure", "infrastructural", "instructive", "instrumental"], "infrastructure"),
    487: ("Describing the loss as a small setback was a clear ____.",
          ["understatement", "understated", "understanding", "undertaking"], "understatement"),
    488: ("Analysts blamed the CEO's ____ for the failed expansion.",
          ["hubris", "humility", "humour", "hurdle"], "hubris"),
    489: ("Please ____ all expenses with original receipts.",
          ["document", "documentary", "documentation", "documented"], "document"),
    490: ("The presenter's ____ remarks made the audience laugh during the briefing.",
          ["facetious", "facetiously", "facetiousness", "factious"], "facetious"),
    258: ("The head of the department asked ____ the final report on Friday.",
          ["for", "to", "at", "of"], "for"),
    311: ("The new assistant manager is responsible ____ training the summer interns.",
          ["for", "of", "to", "with"], "for"),
    312: ("Ms. Chen has worked in the accounting department ____ 2019.",
          ["since", "for", "from", "during"], "since"),
    313: ("All staff members are required to ____ their identification badges.",
          ["wear", "wearing", "wore", "worn"], "wear"),
    314: ("The shipment will be delivered ____ the end of the week.",
          ["by", "until", "since", "during"], "by"),
    315: ("Neither the manager nor the assistants ____ available for the conference call.",
          ["were", "was", "is", "has been"], "were"),
    316: ("The company's profits have grown ____ since the new CEO took over.",
          ["considerably", "considerable", "consideration", "considerate"], "considerably"),
    317: ("Please ____ your laptop and put it in your bag before leaving the meeting room.",
          ["shut down", "shut in", "shut out", "shut away"], "shut down"),
    318: ("The invoice must be paid within 30 days; ____, a late fee will be charged.",
          ["otherwise", "therefore", "moreover", "likewise"], "otherwise"),
    319: ("Ms. Rivera is the only employee ____ has access to the client database.",
          ["who", "whom", "which", "whose"], "who"),
    320: ("The training session was ____ useful that the company scheduled a second one.",
          ["so", "such", "too", "very"], "so"),
    343: ("If the flight ____ delayed, we will hold the meeting online.",
          ["is", "will be", "being", "were"], "is"),
    347: ("The board of directors decided to ____ the merger until further notice.",
          ["put off", "put up", "put on", "put out"], "put off"),
    356: ("Mr. Okafor ____ the sales figures when the client called.",
          ["was reviewing", "review", "reviews", "has reviewed"], "was reviewing"),
    361: ("The office ____ on the fifth floor of the Meridian Building.",
          ["is located", "locates", "locating", "is locating"], "is located"),
    362: ("By the time the auditors arrived, the staff ____ all the documents.",
          ["had prepared", "prepare", "have prepared", "prepares"], "had prepared"),
    363: ("We would appreciate it if you ____ the contract by Friday.",
          ["could sign", "can signing", "will sign", "sign"], "could sign"),
    365: ("The department store is larger than ____ in the shopping district.",
          ["any other store", "any store", "any stores", "other store"], "any other store"),
    366: ("All travel expenses must be approved ____ the trip takes place.",
          ["before", "until", "while", "during"], "before"),
    367: ("The marketing manager suggested ____ the advertising campaign online.",
          ["launching", "launch", "to launch", "launched"], "launching"),
    369: ("The new software is designed to help employees ____ their tasks more efficiently.",
          ["complete", "completing", "completed", "completion"], "complete"),
    370: ("The customer service team handles ____ complaints every day.",
          ["hundreds of", "hundred of", "hundreds", "a hundred of"], "hundreds of"),
    403: ("The seminar will be held ____ the second floor of the conference centre.",
          ["on", "in", "at", "by"], "on"),
    408: ("The sales figures for April were ____ than those for March.",
          ["higher", "high", "highest", "highly"], "higher"),
    412: ("Each department must submit ____ quarterly report by the fifth of the month.",
          ["its", "their", "it's", "they're"], "its"),
    418: ("The delivery truck ____ at the warehouse at 7 a.m. every morning.",
          ["arrives", "arrive", "arriving", "is arrive"], "arrives"),
    422: ("The committee will announce the winner ____ the awards dinner.",
          ["during", "while", "among", "between"], "during"),
    424: ("Mr. Dubois is ____ for negotiating contracts with overseas suppliers.",
          ["responsible", "responsibility", "responsibly", "responsive"], "responsible"),
    428: ("The maintenance crew ____ the air conditioners twice a year.",
          ["inspects", "inspection", "inspector", "inspected"], "inspects"),
    430: ("The proposal was rejected ____ it exceeded the department's budget.",
          ["because", "although", "unless", "despite"], "because"),
    447: ("Ms. Kim will ____ the client at the airport tomorrow morning.",
          ["meet", "meets", "met", "meeting"], "meet"),
    473: ("The staff was reminded ____ the safety procedures at all times.",
          ["to follow", "follow", "following", "followed"], "to follow"),
    479: ("The hotel offers a shuttle service ____ guests to the convention centre.",
          ["taking", "takes", "took", "take"], "taking"),
}

# --- duplicates and items whose options were not real words ------------------
FIXUPS = {
    803: ("The intern was asked to ____ the meeting minutes and circulate them.",
          ["take", "takes", "taking", "took"], "take"),
    857: ("The new recruits will ____ a two-week training programme in July.",
          ["attend", "attends", "attending", "attendance"], "attend"),
    869: ("The board approved a generous ____ for the retiring director.",
          ["severance package", "severance packaged", "severing package", "several package"], "severance package"),
    58: ("The seminar was ____ long that several participants left early.",
         ["so", "such", "too", "very"], "so"),
    210: ("The marketing materials were ____ for the trade show by 6 a.m.",
          ["ready", "readily", "readiness", "readied"], "ready"),
    396: ("The figures in the draft report ____ incorrect, so please verify them.",
          ["may be", "maybe", "perhaps", "probably"], "may be"),
    478: ("The caterer ordered fresh ____ for the company lunch.",
          ["vegetables", "vegetable", "vegetated", "vegetating"], "vegetables"),
}

REPLACEMENTS = {}
REPLACEMENTS.update(P6)
REPLACEMENTS.update(GRAMMAR)
REPLACEMENTS.update(FIXUPS)
