# -*- coding: utf-8 -*-
# Part D: lessons 39-50
CATS_D = {
"Hotels": [
("advance","заранее","사전에","Book your room in advance.","Забронируйте номер заранее.","객실을 사전에 예약하세요."),
("chain","сеть (отелей)","체인","The hotel is part of a chain.","Отель входит в сеть.","그 호텔은 체인의 일부입니다."),
("check in","зарегистрироваться, заселиться","체크인하다","Check in after 3 PM.","Заселяйтесь после 15:00.","오후 3시 이후에 체크인하세요."),
("confirm","подтверждать","확인하다","Confirm your reservation by email.","Подтвердите бронирование по электронной почте.","이메일로 예약을 확인하세요."),
("expect","ожидать","기대하다","Guests expect clean rooms.","Гости ожидают чистые номера.","고객은 깨끗한 객실을 기대합니다."),
("housekeeper","горничная","하우스키퍼","The housekeeper cleans the rooms.","Горничная убирает номера.","하우스키퍼가 객실을 청소합니다."),
("notify","уведомлять","알리다","Notify the front desk of any issue.","Сообщайте о проблемах на стойку регистрации.","문제가 있으면 프런트에 알리세요."),
("preclude","исключать, препятствовать","막다","The renovation may preclude booking.","Ремонт может помешать бронированию.","리노베이션이 예약을 막을 수 있습니다."),
("quote","называть цену","견적을 내다","The clerk quoted the nightly rate.","Сотрудник назвал цену за ночь.","직원이 1박 요금을 견적했습니다."),
("rate","тариф","요금","The weekend rate is higher.","Тариф в выходные выше.","주말 요금이 더 높습니다."),
("reserve","бронировать, резервировать","예약하다","Reserve a room for two nights.","Забронируйте номер на две ночи.","2박 객실을 예약하세요."),
("service","обслуживание, сервис","서비스","The hotel offers room service.","Отель предлагает обслуживание номеров.","호텔이 룸서비스를 제공합니다."),
],
"Car Rentals": [
("busy","занятой","바쁜","The rental office was busy all day.","Офис проката был занят весь день.","렌탈 사무실은 하루 종일 바빴습니다."),
("coincide","совпадать","일치하다","My trip coincided with the holiday.","Моя поездка совпала с праздником.","내 여행이 휴일과 일치했습니다."),
("confusion","путаница","혼란","There was confusion about the pickup time.","Была путаница со временем получения машины.","픽업 시간에 혼란이 있었습니다."),
("contact","связываться","연락하다","Contact the office to reserve a car.","Свяжитесь с офисом, чтобы забронировать машину.","차를 예약하려면 사무실에 연락하세요."),
("disappoint","разочаровывать","실망시키다","The service did not disappoint us.","Сервис нас не разочаровал.","서비스는 우리를 실망시키지 않았습니다."),
("intend","намереваться","의도하다","I intend to rent a car for the weekend.","Я намереваюсь арендовать машину на выходные.","나는 주말에 차를 빌릴 의도입니다."),
("license","права, лицензия","면허","You need a valid license to rent.","Для аренды нужны действующие права.","렌탈에는 유효한 면허가 필요합니다."),
("nervous","нервный","긴장한","He was nervous about driving in traffic.","Он нервничал из-за вождения в потоке.","그는 교통 속 운전에 긴장했습니다."),
("optional","необязательный","선택 사항인","Insurance is optional for renters.","Страховка для арендаторов необязательна.","보험은 렌터 이용자에게 선택 사항입니다."),
("tempt","соблазнять","유혹하다","The offer tempted me to rent a larger car.","Предложение соблазнило меня арендовать машину побольше.","그 제안이 더 큰 차를 빌리도록 유혹했습니다."),
("thrill","волнение, острые ощущения","스릴","Driving along the coast was a thrill.","Езда вдоль побережья была настоящим волнением.","해안을 따라 운전하는 것은 스릴이었습니다."),
("tier","уровень, класс","등급","They rent cars at every tier.","Они сдают машины любого класса.","그들은 모든 등급의 차를 렌트합니다."),
],
"Movies": [
("attain","достигать","달성하다","The film attained great popularity.","Фильм достиг большой популярности.","그 영화는 큰 인기를 달성했습니다."),
("combine","объединять","결합하다","The movie combines drama and comedy.","Фильм объединяет драму и комедию.","그 영화는 드라마와 코미디를 결합합니다."),
("continue","продолжать","계속하다","The series continued for years.","Сериал продолжался годами.","시리즈는 몇 년 동안 계속되었습니다."),
("description","описание","묘사","The description matches the plot.","Описание соответствует сюжету.","묘사가 줄거리와 일치합니다."),
("disperse","рассеиваться","흩어지다","The crowd dispersed after the show.","Толпа рассеялась после шоу.","공연 후 군중이 흩어졌습니다."),
("entertainment","развлечение","오락","The film is pure entertainment.","Фильм — чистое развлечение.","그 영화는 순수한 오락입니다."),
("influence","влияние","영향","The director influenced many filmmakers.","Режиссёр повлиял на многих кинематографистов.","그 감독은 많은 영화 제작자에게 영향을 미쳤습니다."),
("range","диапазон, круг","범위","The movie appeals to a wide range of viewers.","Фильм привлекает широкий круг зрителей.","그 영화는 다양한 관객층에게 어필합니다."),
("release","выпускать, премьера","개봉하다","The studio released the film on Friday.","Студия выпустила фильм в пятницу.","스튜디오가 금요일에 그 영화를 개봉했습니다."),
("represent","представлять","나타내다","The film represents a new trend.","Фильм представляет новый тренд.","그 영화는 새로운 경향을 나타냅니다."),
("separate","отдельный","별개의","The episodes are separate stories.","Эпизоды — отдельные истории.","에피소드는 별개의 이야기입니다."),
("successive","последовательный","연속적인","The movie was a hit for three successive weeks.","Фильм был хитом три недели подряд.","그 영화는 3주 연속 히트였습니다."),
],
"Theater": [
("action","действие","행동","The play's action takes place in one room.","Действие пьесы происходит в одной комнате.","연극의 행동은 한 방에서 일어납니다."),
("approach","подход","접근 방식","The director took a new approach.","Режиссёр применил новый подход.","감독이 새로운 접근 방식을 취했습니다."),
("audience","зрители, аудитория","관객","The audience applauded loudly.","Зрители громко аплодировали.","관객이 크게 박수를 쳤습니다."),
("create","создавать","창조하다","The playwright created a great story.","Драматург создал великолепную историю.","극작가가 훌륭한 이야기를 창조했습니다."),
("dialogue","диалог","대사","The dialogue was well written.","Диалоги были хорошо написаны.","대사가 잘 쓰였습니다."),
("element","элемент","요소","Music is a key element of the show.","Музыка — ключевой элемент шоу.","음악은 쇼의 핵심 요소입니다."),
("experience","опыт, переживание","경험","The play was a memorable experience.","Спектакль стал незабываемым опытом.","그 연극은 기억에 남는 경험이었습니다."),
("occur","происходить","일어나다","The performance occurs nightly.","Представление проходит каждый вечер.","공연이 매일 밤 열립니다."),
("perform","выступать, исполнять","공연하다","The actors perform twice a day.","Актёры выступают дважды в день.","배우들이 하루 두 번 공연합니다."),
("rehearse","репетировать","리허설하다","The cast rehearsed for weeks.","Труппа репетировала неделями.","출연진이 몇 주간 리허설했습니다."),
("review","рецензия, обзор","평론","The play received good reviews.","Спектакль получил хорошие рецензии.","그 연극은 좋은 평론을 받았습니다."),
("sold out","распроданный","매진된","The show is sold out.","Билеты на шоу распроданы.","그 공연은 매진되었습니다."),
],
"Music": [
("available","доступный","이용 가능한","The album is available in stores.","Альбом доступен в магазинах.","그 앨범은 매장에서 구할 수 있습니다."),
("broad","широкий","넓은","The song appeals to a broad audience.","Песня нравится широкой аудитории.","그 노래는 넓은 관객에게 어필합니다."),
("category","категория","범주","Jazz is one category of music.","Джаз — одна из категорий музыки.","재즈는 음악의 한 범주입니다."),
("disparate","разнородный","이질적인","The album mixes disparate styles.","Альбом смешивает разнородные стили.","그 앨범은 이질적인 스타일을 섞습니다."),
("divide","делить","나누다","The music was divided into two parts.","Музыка была разделена на две части.","음악은 두 부분으로 나뉘었습니다."),
("favorite","любимый","가장 좋아하는","That song is my favorite.","Эта песня — моя любимая.","그 노래는 내가 가장 좋아하는 곡입니다."),
("instinct","инстинкт","본능","He has an instinct for rhythm.","У него инстинкт к ритму.","그는 리듬에 대한 본능이 있습니다."),
("preference","предпочтение","선호","She has a preference for jazz.","Она предпочитает джаз.","그녀는 재즈를 선호합니다."),
("reason","причина","이유","There is no reason to miss the show.","Нет причины пропустить шоу.","그 공연을 놓칠 이유가 없습니다."),
("relaxation","отдых, расслабление","휴식","Music provides relaxation.","Музыка даёт отдых.","음악은 휴식을 제공합니다."),
("taste","вкус, предпочтение","취향","She has good taste in music.","У неё хороший вкус в музыке.","그녀는 음악 취향이 좋습니다."),
("urge","побуждать","촉구하다","He urged the band to record faster.","Он побуждал группу записываться быстрее.","그는 밴드가 더 빨리 녹음하도록 촉구했습니다."),
],
"Museums": [
("acquire","приобретать","획득하다","The museum acquired a rare painting.","Музей приобрёл редкую картину.","박물관이 희귀한 그림을 획득했습니다."),
("admire","восхищаться","감탄하다","Visitors admire the collection.","Посетители восхищаются коллекцией.","방문객들이 소장품에 감탄합니다."),
("collection","коллекция","소장품","The collection includes ancient art.","Коллекция включает древнее искусство.","소장품에는 고대 미술이 포함됩니다."),
("criticism","критика","비평","The exhibition drew both praise and criticism.","Выставка вызвала и похвалу, и критику.","그 전시는 칭찬과 비평을 모두 불러일으켰습니다."),
("express","выражать","표현하다","The art expresses deep emotion.","Искусство выражает глубокие эмоции.","그 미술은 깊은 감정을 표현합니다."),
("fashion","мода","유행","The style never went out of fashion.","Стиль никогда не выходил из моды.","그 스타일은 유행이 지나지 않았습니다."),
("leisure","досуг","여가","We visited the museum at our leisure.","Мы посетили музей на досуге.","우리는 여가 시간에 박물관을 방문했습니다."),
("respond","отвечать, реагировать","응답하다","Visitors responded well to the exhibit.","Посетители хорошо отреагировали на экспозицию.","방문객들은 전시에 잘 반응했습니다."),
("schedule","планировать","일정을 잡다","The museum scheduled a new tour.","Музей запланировал новую экскурсию.","박물관이 새 투어 일정을 잡았습니다."),
("significant","значительный","중요한","The donation was significant.","Пожертвование было значительным.","기부는 상당했습니다."),
("specialize","специализироваться","전문으로 하다","The museum specializes in modern art.","Музей специализируется на современном искусстве.","그 박물관은 현대 미술을 전문으로 합니다."),
("spectrum","спектр","범위","The gallery covers a wide spectrum of styles.","Галерея охватывает широкий спектр стилей.","그 갤러리는 다양한 스타일 범위를 다룹니다."),
],
"Media": [
("assignment","задание","과제","The reporter is on assignment abroad.","Репортёр в командировке за границей.","기자가 해외 취재 중입니다."),
("choose","выбирать","선택하다","The editor chose the headline.","Редактор выбрал заголовок.","편집자가 헤드라인을 선택했습니다."),
("constant","постоянный","꾸준한","The station gets constant news updates.","Станция получает постоянные обновления новостей.","방송국은 꾸준한 뉴스 업데이트를 받습니다."),
("constitute","составлять","구성하다","Investigative stories constitute most of the program.","Расследовательские репортажи составляют большую часть программы.","취재 보도가 프로그램의 대부분을 구성합니다."),
("decisive","решающий","결정적인","The editor made a decisive call.","Редактор принял решающее решение.","편집자가 결정적인 판단을 했습니다."),
("disseminate","распространять","퍼뜨리다","The network disseminates news worldwide.","Сеть распространяет новости по всему миру.","네트워크가 전 세계로 뉴스를 퍼뜨립니다."),
("impact","влияние","영향","The report had a strong impact.","Репортаж оказал сильное влияние.","그 보도는 큰 영향이 있었습니다."),
("in depth","углублённый","심층적인","The program covers the story in depth.","Программа глубоко освещает эту историю.","그 프로그램은 그 사건을 심층적으로 다룹니다."),
("investigative","расследовательский","탐사의","She works in investigative journalism.","Она работает в расследовательской журналистике.","그녀는 탐사 저널리즘 분야에서 일합니다."),
("link","связывать","연결하다","The article links the two events.","Статья связывает два события.","기사가 두 사건을 연결합니다."),
("subscribe","подписываться","구독하다","Thousands subscribe to the news service.","Тысячи подписываются на новостной сервис.","수천 명이 그 뉴스 서비스를 구독합니다."),
("thorough","тщательный","철저한","The magazine did a thorough review.","Журнал провёл тщательный обзор.","그 잡지가 철저한 리뷰를 했습니다."),
],
"Doctors Office": [
("annual","годовой, ежегодный","연례의","You need an annual checkup.","Вам нужен ежегодный осмотр.","연례 건강검진이 필요합니다."),
("appointment","приём, запись","진료 예약","I made an appointment for Monday.","Я записался на приём на понедельник.","나는 월요일에 진료를 예약했습니다."),
("assess","оценивать","평가하다","The doctor will assess your condition.","Врач оценит ваше состояние.","의사가 당신의 상태를 평가할 것입니다."),
("diagnose","диагностировать","진단하다","The doctor diagnosed the illness.","Врач диагностировал болезнь.","의사가 병을 진단했습니다."),
("effective","эффективный","효과적인","The treatment proved effective.","Лечение оказалось эффективным.","그 치료는 효과적인 것으로 밝혀졌습니다."),
("instrument","инструмент","도구","The doctor used sterile instruments.","Врач использовал стерильные инструменты.","의사가 소독된 도구를 사용했습니다."),
("manage","справляться, управлять","관리하다","She manages her symptoms well.","Она хорошо справляется со своими симптомами.","그녀는 증상을 잘 관리합니다."),
("prevent","предотвращать","예방하다","Good habits prevent illness.","Хорошие привычки предотвращают болезни.","좋은 습관이 질병을 예방합니다."),
("recommend","рекомендовать","추천하다","The doctor recommended a specialist.","Врач рекомендовал специалиста.","의사가 전문의를 추천했습니다."),
("record","запись, карта","기록","The clinic keeps a record of visits.","Клиника ведёт записи посещений.","클리닉은 방문 기록을 유지합니다."),
("refer","направлять","의뢰하다","The doctor referred me to a specialist.","Врач направил меня к специалисту.","의사가 나를 전문의에게 의뢰했습니다."),
("serious","серьёзный","심각한","It was a serious condition.","Это было серьёзное состояние.","그것은 심각한 상태였습니다."),
],
"Dentists Office": [
("aware","осознающий","인지하는","Be aware of your oral health.","Осознавайте важность здоровья полости рта.","구강 건강을 인지하세요."),
("catch up","наверстать","따라잡다","Patients should catch up on dental visits.","Пациентам стоит наверстать визиты к стоматологу.","환자는 치과 방문을 따라잡아야 합니다."),
("distraction","отвлечение","방해","The office is a distraction-free zone.","В кабинете нет отвлекающих факторов.","그 진료실은 방해 요인이 없는 곳입니다."),
("encouragement","ободрение","격려","The dentist gave patients encouragement.","Стоматолог поддерживал пациентов.","치과의사가 환자에게 격려를 주었습니다."),
("evident","очевидный","명백한","Improvement was evident after treatment.","Улучшение было очевидным после лечения.","치료 후 개선이 명백했습니다."),
("habit","привычка","습관","Brushing daily is a good habit.","Ежедневная чистка — хорошая привычка.","매일 양치질하는 것은 좋은 습관입니다."),
("illuminate","освещать","밝히다","The dentist illuminated the mouth to check the teeth.","Стоматолог осветил полость рта, чтобы проверить зубы.","치과의사가 치아를 확인하기 위해 입을 밝혔습니다."),
("irritate","раздражать","자극하다","The gum may irritate sensitive teeth.","Десна может раздражать чувствительные зубы.","잇몸이 민감한 치아를 자극할 수 있습니다."),
("overview","обзор","개요","The dentist gave an overview of the treatment.","Стоматолог дал обзор лечения.","치과의사가 치료 개요를 설명했습니다."),
("position","положение","위치","The position of the tooth is unusual.","Положение зуба необычное.","그 치아의 위치가 특이합니다."),
("regularly","регулярно","정기적으로","Visit the dentist regularly.","Посещайте стоматолога регулярно.","치과에 정기적으로 방문하세요."),
("restore","восстанавливать","회복시키다","The dentist restored the damaged tooth.","Стоматолог восстановил повреждённый зуб.","치과의사가 손상된 치아를 회복시켰습니다."),
],
"Health Insurance": [
("allow","позволять","허용하다","The plan allows two checkups a year.","План позволяет два осмотра в год.","그 보험은 연간 검진 2회를 허용합니다."),
("alternative","альтернатива","대안","The policy offers alternative coverage.","Полис предлагает альтернативное покрытие.","그 보험은 대체 보장을 제공합니다."),
("aspect","аспект","측면","Consider every aspect of the policy.","Учитывайте каждый аспект полиса.","보험의 모든 측면을 고려하세요."),
("concern","беспокойство","우려","Cost is a major concern for members.","Стоимость — главное беспокойство для участников.","비용은 가입자에게 주요 우려 사항입니다."),
("emphasize","подчёркивать","강조하다","The provider emphasized prevention.","Поставщик подчеркнул профилактику.","제공자는 예방을 강조했습니다."),
("incur","нести (расходы)","발생시키다","You may incur extra charges.","Вы можете понести дополнительные расходы.","추가 비용이 발생할 수 있습니다."),
("personnel","персонал","직원","Company personnel get group coverage.","Сотрудники компании получают коллективное покрытие.","회사 직원은 단체 보장을 받습니다."),
("policy","полис, политика","보험 증권","Read the policy before signing.","Прочитайте полис перед подписанием.","서명하기 전에 보험 증권을 읽으세요."),
("portion","часть","부분","The insurer pays a portion of the cost.","Страховщик оплачивает часть стоимости.","보험사가 비용의 일부를 지불합니다."),
("regardless","независимо от","~와 관계없이","Coverage continues regardless of age.","Покрытие продолжается независимо от возраста.","보장은 나이와 관계없이 계속됩니다."),
("salary","зарплата","급여","Health insurance is part of the salary package.","Медицинская страховка — часть зарплатного пакета.","건강보험은 급여 패키지의 일부입니다."),
("suitable","подходящий","적합한","Find a plan suitable for your needs.","Найдите план, подходящий вашим потребностям.","당신의 필요에 적합한 플랜을 찾으세요."),
],
"Hospitals": [
("admit","принимать (в больницу)","입원시키다","The patient was admitted overnight.","Пациент был госпитализирован на ночь.","환자가 밤새 입원했습니다."),
("authorization","разрешение","승인","The insurer gave authorization for surgery.","Страховщик дал разрешение на операцию.","보험사가 수술을 승인했습니다."),
("designate","назначать, указывать","지정하다","The doctor designated the treatment.","Врач назначил лечение.","의사가 치료를 지정했습니다."),
("escort","сопровождение","안내","An escort led us to the ward.","Сопровождающий провёл нас в палату.","안내자가 우리를 병동으로 안내했습니다."),
("identify","опознавать","확인하다","The bracelet helps identify the patient.","Браслет помогает опознать пациента.","팔찌가 환자를 확인하는 데 도움이 됩니다."),
("mission","миссия","사명","Our mission is patient care.","Наша миссия — забота о пациентах.","우리의 사명은 환자 돌봄입니다."),
("permit","разрешать","허가하다","Visiting is not permitted after 8.","Посещения не разрешены после 8 часов.","8시 이후에는 방문이 허가되지 않습니다."),
("pertinent","относящийся к делу","관련 있는","Give the doctor all pertinent information.","Дайте врачу всю относящуюся к делу информацию.","의사에게 관련 정보를 모두 주세요."),
("procedure","процедура","절차","The procedure is standard.","Процедура стандартная.","그 절차는 표준입니다."),
("result","результат","결과","The test results came back.","Пришли результаты анализов.","검사 결과가 나왔습니다."),
("statement","выписка, счёт","명세서","The hospital sent a billing statement.","Больница прислала счёт.","병원이 청구 명세서를 보냈습니다."),
("usual","обычный","평소의","We followed the usual procedure.","Мы следовали обычной процедуре.","우리는 평소 절차를 따랐습니다."),
],
"Pharmacy": [
("consult","консультироваться","상담하다","Consult the pharmacist about the drug.","Проконсультируйтесь с фармацевтом насчёт лекарства.","약에 대해 약사와 상담하세요."),
("control","контролировать","통제하다","The pharmacy controls its inventory.","Аптека контролирует свои запасы.","약국이 재고를 통제합니다."),
("convenient","удобный","편리한","The pharmacy has convenient hours.","У аптеки удобные часы работы.","그 약국은 영업 시간이 편리합니다."),
("detect","обнаруживать","감지하다","The test detects the condition early.","Тест обнаруживает состояние на ранней стадии.","그 검사는 상태를 조기에 감지합니다."),
("factor","фактор","요인","Dosage depends on several factors.","Дозировка зависит от нескольких факторов.","복용량은 여러 요인에 달려 있습니다."),
("interaction","взаимодействие","상호작용","Ask about drug interactions.","Спросите о взаимодействии лекарств.","약물 상호작용에 대해 물어보세요."),
("limit","предел","한도","There is a limit on refills.","Есть предел на повторные выдачи.","리필에는 한도가 있습니다."),
("monitor","отслеживать","모니터링하다","Monitor your reaction to the medicine.","Отслеживайте свою реакцию на лекарство.","약에 대한 반응을 모니터링하세요."),
("potential","потенциальный","잠재적인","The drug has potential side effects.","У лекарства есть потенциальные побочные эффекты.","그 약에는 잠재적인 부작용이 있습니다."),
("sample","образец","샘플","The pharmacist gave a free sample.","Фармацевт дал бесплатный образец.","약사가 무료 샘플을 주었습니다."),
("sense","смысл, чувство","감각","Use common sense with dosage.","Пользуйтесь здравым смыслом при дозировке.","복용량에 상식을 사용하세요."),
("volunteer","доброволец","자원봉사자","Volunteers help distribute the medication.","Добровольцы помогают раздавать лекарства.","자원봉사자들이 약품 배포를 돕습니다."),
],
}
