# -*- coding: utf-8 -*-
# Part A: lessons 1-13 (Barron's 600 Essential Words for the TOEIC)
# Each entry: (eng, rus, kor, exampleEng, exampleRus, exampleKor)
CATS_A = {
"Contracts": [
("abide by","соблюдать","준수하다","You must abide by the company rules.","Вы должны соблюдать правила компании.","회사 규칙을 준수해야 합니다."),
("agreement","соглашение","합의","They reached an agreement about the contract.","Они достигли соглашения по контракту.","그들은 계약에 대한 합의에 도달했습니다."),
("assurance","гарантия, заверение","보증","We received assurance of delivery.","Мы получили гарантию доставки.","우리는 배송 보증을 받았습니다."),
("cancel","отменять","취소하다","We must cancel the meeting.","Мы должны отменить встречу.","회의를 취소해야 합니다."),
("determine","определять","결정하다","We need to determine the cause.","Нам нужно определить причину.","원인을 결정해야 합니다."),
("engage","нанимать, привлекать","고용하다","We engaged a new consultant.","Мы наняли нового консультанта.","우리는 새로운 컨설턴트를 고용했습니다."),
("establish","устанавливать","설립하다","They established a new branch.","Они открыли новый филиал.","그들은 새로운 지사를 설립했습니다."),
("obligate","обязывать","의무를 지우다","The contract obligates us to deliver.","Контракт обязывает нас доставить.","계약은 우리에게 배달 의무를 지웁니다."),
("party","сторона (в договоре)","당사자","Both parties signed the agreement.","Обе стороны подписали соглашение.","양 당사자가 계약에 서명했습니다."),
("provision","положение, пункт","조항","Read the provision carefully.","Внимательно прочитайте положение.","조항을 주의 깊게 읽으십시오."),
("resolve","разрешать (спор)","해결하다","We resolved the dispute out of court.","Мы разрешили спор без суда.","우리는 분쟁을 법정 밖에서 해결했습니다."),
("specify","указывать, оговаривать","명시하다","The contract specifies the delivery date.","В контракте указана дата поставки.","계약서에 배송 날짜가 명시되어 있습니다."),
],
"Marketing": [
("attract","привлекать","끌어들이다","The campaign attracted new customers.","Кампания привлекла новых клиентов.","캠페인이 새로운 고객을 끌어들였습니다."),
("compare","сравнивать","비교하다","Compare the two products carefully.","Сравните два продукта внимательно.","두 제품을 주의 깊게 비교하세요."),
("compete","конкурировать","경쟁하다","We compete in the global market.","Мы конкурируем на глобальном рынке.","우리는 세계 시장에서 경쟁합니다."),
("consume","потреблять","소비하다","Consumers use the product daily.","Потребители используют продукт ежедневно.","소비자들이 그 제품을 매일 사용합니다."),
("convince","убеждать","설득하다","The ad convinced customers to switch brands.","Реклама убедила клиентов сменить бренд.","광고가 고객이 브랜드를 바꾸도록 설득했습니다."),
("current","текущий, актуальный","현재의","Our current sales are strong.","Наши текущие продажи высоки.","현재 판매가 강세입니다."),
("fad","модное увлечение","일시적 유행","That toy was just a fad.","Та игрушка была лишь мимолётной модой.","그 장난감은 일시적인 유행에 불과했습니다."),
("inspire","вдохновлять","영감을 주다","The product inspired customer loyalty.","Продукт вдохновил лояльность клиентов.","그 제품은 고객 충성도를 불러일으켰습니다."),
("market","рынок","시장","The market is competitive.","Рынок конкурентен.","시장이 경쟁적입니다."),
("persuade","убеждать","설득하다","We persuaded them to buy.","Мы убедили их купить.","우리는 그들이 구매하도록 설득했습니다."),
("productive","продуктивный, результативный","생산적인","The team had a productive meeting.","У команды была продуктивная встреча.","팀이 생산적인 회의를 했습니다."),
("satisfy","удовлетворять","만족시키다","The service satisfied all customers.","Сервис удовлетворил всех клиентов.","서비스가 모든 고객을 만족시켰습니다."),
],
"Warranties": [
("characteristic","характеристика","특징","Durability is a key characteristic of the product.","Долговечность — ключевая характеристика продукта.","내구성은 그 제품의 핵심 특징입니다."),
("consequence","последствие","결과","Misuse has serious consequences.","Неправильное использование влечёт серьёзные последствия.","오용은 심각한 결과를 초래합니다."),
("consider","рассматривать, обдумывать","고려하다","Consider the warranty before buying.","Обдумайте гарантию перед покупкой.","구매 전에 보증을 고려하세요."),
("cover","покрывать (страховкой/гарантией)","보장하다","The warranty covers all repairs.","Гарантия покрывает весь ремонт.","보증이 모든 수리를 보장합니다."),
("expire","истекать","만료되다","The warranty expires after 24 months.","Гарантия истекает через 24 месяца.","보증은 24개월 후에 만료됩니다."),
("frequent","частый","빈번한","Frequent use caused the damage.","Частое использование вызвало повреждение.","빈번한 사용이 손상을 일으켰습니다."),
("imply","подразумевать","암시하다","The warranty implies certain rights.","Гарантия подразумевает определённые права.","보증은 특정 권리를 암시합니다."),
("promise","обещать","약속하다","They promise a full refund.","Они обещают полный возврат средств.","그들은 전액 환불을 약속합니다."),
("protect","защищать","보호하다","The warranty protects the buyer.","Гарантия защищает покупателя.","보증이 구매자를 보호합니다."),
("reputation","репутация","평판","The company has a good reputation.","У компании хорошая репутация.","그 회사는 평판이 좋습니다."),
("require","требовать","요구하다","The warranty requires proof of purchase.","Для гарантии требуется подтверждение покупки.","보증에는 구매 증빙이 필요합니다."),
("vary","различаться, варьироваться","다르다","Coverage varies by product.","Покрытие различается в зависимости от продукта.","보장 범위는 제품마다 다릅니다."),
],
"Business Planning": [
("address","рассматривать, решать (вопрос)","다루다","We must address the budget issue.","Мы должны решить вопрос бюджета.","예산 문제를 다루어야 합니다."),
("avoid","избегать","피하다","Avoid unnecessary costs.","Избегайте ненужных расходов.","불필요한 비용을 피하세요."),
("demonstrate","демонстрировать, показывать","입증하다","The data demonstrates strong growth.","Данные показывают уверенный рост.","데이터가 강한 성장을 입증합니다."),
("develop","разрабатывать","개발하다","We will develop a new strategy.","Мы разработаем новую стратегию.","우리는 새로운 전략을 개발할 것입니다."),
("evaluate","оценивать","평가하다","Evaluate the proposal carefully.","Тщательно оцените предложение.","제안을 신중하게 평가하세요."),
("gather","собирать","모으다","Gather all the relevant data.","Соберите все необходимые данные.","관련 데이터를 모두 모으세요."),
("offer","предлагать","제공하다","We offer a competitive price.","Мы предлагаем конкурентоспособную цену.","우리는 경쟁력 있는 가격을 제공합니다."),
("primary","основной, главный","주된","Our primary goal is growth.","Наша главная цель — рост.","우리의 주된 목표는 성장입니다."),
("risk","риск","위험","There is some risk in the plan.","В плане есть некоторый риск.","그 계획에는 약간의 위험이 있습니다."),
("strategy","стратегия","전략","Develop a growth strategy.","Разработайте стратегию роста.","성장 전략을 수립하세요."),
("strong","сильный, надёжный","강력한","The company has strong sales.","У компании сильные продажи.","회사는 판매가 강력합니다."),
("substitute","заменитель","대체물","Use a cheaper substitute.","Используйте более дешёвый заменитель.","더 저렴한 대체물을 사용하세요."),
],
"Conferences": [
("accommodate","размещать","수용하다","We can accommodate 200 guests.","Мы можем разместить 200 гостей.","우리는 200명의 손님을 수용할 수 있습니다."),
("arrangement","договорённость, подготовка","준비","The travel arrangement is confirmed.","Договорённость о поездке подтверждена.","여행 준비가 확정되었습니다."),
("association","ассоциация","협회","The association held a conference.","Ассоциация провела конференцию.","협회가 컨퍼런스를 개최했습니다."),
("attend","посещать, присутствовать","참석하다","Many experts will attend the event.","Многие эксперты посетят мероприятие.","많은 전문가가 행사에 참석할 것입니다."),
("get in touch","связаться","연락하다","Get in touch with the organizer.","Свяжитесь с организатором.","주최자에게 연락하세요."),
("hold","проводить (мероприятие)","개최하다","They will hold the meeting in May.","Они проведут встречу в мае.","그들은 5월에 회의를 개최할 것입니다."),
("location","местоположение","장소","The location is easy to find.","Место легко найти.","장소를 찾기 쉽습니다."),
("overcrowded","переполненный","혼잡한","The hall was overcrowded.","Зал был переполнен.","회의장이 혼잡했습니다."),
("register","регистрироваться","등록하다","Register for the conference online.","Зарегистрируйтесь на конференцию онлайн.","온라인으로 컨퍼런스에 등록하세요."),
("select","выбирать","선택하다","Select a convenient date.","Выберите удобную дату.","편리한 날짜를 선택하세요."),
("session","заседание, сессия","세션","The morning session starts at nine.","Утреннее заседание начинается в девять.","오전 세션은 9시에 시작합니다."),
("take part in","принимать участие","참여하다","Many companies take part in the fair.","Многие компании участвуют в выставке.","많은 회사가 박람회에 참여합니다."),
],
"Computers": [
("access","доступ","접근","You need access to the system.","Вам нужен доступ к системе.","시스템에 접근해야 합니다."),
("allocate","выделять, распределять","할당하다","Allocate memory to the program.","Выделите память программе.","프로그램에 메모리를 할당하세요."),
("compatible","совместимый","호환되는","The software is compatible with our system.","Программа совместима с нашей системой.","그 소프트웨어는 우리 시스템과 호환됩니다."),
("delete","удалять","삭제하다","Delete old files to free up space.","Удалите старые файлы, чтобы освободить место.","공간을 확보하려면 오래된 파일을 삭제하세요."),
("display","отображать","표시하다","The screen displays the results.","Экран отображает результаты.","화면에 결과가 표시됩니다."),
("duplicate","дублировать","복제하다","Duplicate the file before editing.","Продублируйте файл перед редактированием.","편집 전에 파일을 복제하세요."),
("fail","выходить из строя","고장 나다","The server may fail under load.","Сервер может выйти из строя под нагрузкой.","서버가 과부하로 고장 날 수 있습니다."),
("figure out","выяснять, понимать","알아내다","Figure out why the program crashed.","Выясните, почему программа дала сбой.","프로그램이 왜 멈췄는지 알아내세요."),
("ignore","игнорировать","무시하다","Do not ignore the error message.","Не игнорируйте сообщение об ошибке.","오류 메시지를 무시하지 마세요."),
("search","искать","검색하다","Search the database for the record.","Найдите запись в базе данных.","데이터베이스에서 기록을 검색하세요."),
("shut down","выключать","종료하다","Shut down the computer properly.","Правильно выключите компьютер.","컴퓨터를 올바르게 종료하세요."),
("warn","предупреждать","경고하다","The system warns about low storage.","Система предупреждает о нехватке памяти.","시스템이 저장 공간 부족을 경고합니다."),
],
"Office Technology": [
("affordable","доступный по цене","저렴한","We need affordable equipment.","Нам нужно недорогое оборудование.","저렴한 장비가 필요합니다."),
("as needed","по мере необходимости","필요에 따라","Order supplies as needed.","Заказывайте материалы по мере необходимости.","필요에 따라 물품을 주문하세요."),
("be in charge of","отвечать за","~을 담당하다","She is in charge of the printers.","Она отвечает за принтеры.","그녀가 프린터를 담당합니다."),
("capacity","ёмкость, вместимость","용량","The drive has a large capacity.","У диска большая ёмкость.","드라이브의 용량이 큽니다."),
("durable","прочный, долговечный","내구성 있는","This keyboard is very durable.","Эта клавиатура очень долговечна.","이 키보드는 매우 내구성이 있습니다."),
("initiative","инициатива","주도권","She showed great initiative.","Она проявила большую инициативу.","그녀는 뛰어난 주도권을 보였습니다."),
("physical","физический, материальный","물리적인","We need physical storage space.","Нам нужно физическое место для хранения.","물리적 저장 공간이 필요합니다."),
("provider","поставщик","공급업체","Our internet provider is reliable.","Наш интернет-провайдер надёжен.","우리 인터넷 공급업체는 신뢰할 수 있습니다."),
("recur","повторяться","반복되다","The error recurs every morning.","Ошибка повторяется каждое утро.","그 오류가 매일 아침 반복됩니다."),
("reduction","сокращение","감소","We saw a reduction in downtime.","Мы заметили сокращение простоев.","가동 중단 시간이 감소했습니다."),
("stay on top of","держать под контролем","계속 파악하다","Stay on top of software updates.","Следите за обновлениями программ.","소프트웨어 업데이트를 계속 파악하세요."),
("stock","запас","재고","We keep enough toner in stock.","Мы держим достаточный запас тонера.","토너를 충분히 재고로 둡니다."),
],
"Office Procedures": [
("appreciate","ценить, быть благодарным","고마워하다","We appreciate your hard work.","Мы ценим вашу усердную работу.","우리는 당신의 노고에 감사드립니다."),
("be exposed to","подвергаться","~에 노출되다","Employees are exposed to new ideas.","Сотрудники знакомятся с новыми идеями.","직원들은 새로운 아이디어에 노출됩니다."),
("bring in","привлекать, вносить","들여오다","The consultant brought in new methods.","Консультант внедрил новые методы.","컨설턴트가 새로운 방법을 들여왔습니다."),
("casual","повседневный, неформальный","캐주얼한","Friday is a casual dress day.","В пятницу — свободный стиль одежды.","금요일은 캐주얼 복장의 날입니다."),
("code","код, свод правил","규정","Follow the dress code.","Соблюдайте дресс-код.","복장 규정을 따르세요."),
("glimpse","мельком увидеть","잠깐 보다","We got a glimpse of the new office.","Мы мельком увидели новый офис.","우리는 새 사무실을 잠깐 보았습니다."),
("made of","сделан из","~로 만들어진","The desk is made of wood.","Стол сделан из дерева.","책상은 나무로 만들어졌습니다."),
("out of","закончиться, без","~이 떨어진","We are out of paper.","У нас закончилась бумага.","종이가 떨어졌습니다."),
("outdated","устаревший","구식의","Replace the outdated forms.","Замените устаревшие бланки.","구식 양식을 교체하세요."),
("practice","практика, обычай","관행","This is standard office practice.","Это стандартная офисная практика.","이것은 표준 사무 관행입니다."),
("reinforce","усиливать","강화하다","Reinforce the new procedures.","Усильте новые процедуры.","새 절차를 강화하세요."),
("verbal","устный, словесный","구두의","We received verbal approval.","Мы получили устное одобрение.","우리는 구두 승인을 받았습니다."),
],
"Electronics": [
("disk","диск","디스크","Store backups on an external disk.","Храните резервные копии на внешнем диске.","백업을 외장 디스크에 저장하세요."),
("facilitate","облегчать, способствовать","촉진하다","Software facilitates the work.","Программа облегчает работу.","소프트웨어가 작업을 촉진합니다."),
("network","сеть","네트워크","Connect to the company network.","Подключитесь к корпоративной сети.","회사 네트워크에 연결하세요."),
("popularity","популярность","인기","The device gained popularity quickly.","Устройство быстро набрало популярность.","그 장치는 빠르게 인기를 얻었습니다."),
("process","обрабатывать","처리하다","The chip processes data fast.","Чип быстро обрабатывает данные.","칩이 데이터를 빠르게 처리합니다."),
("replace","заменять","교체하다","Replace the faulty part.","Замените неисправную деталь.","고장난 부품을 교체하세요."),
("revolution","революция, переворот","혁명","Digital technology was a revolution.","Цифровые технологии стали революцией.","디지털 기술은 혁명이었습니다."),
("sharp","чёткий, резкий","선명한","The monitor has a sharp image.","У монитора чёткое изображение.","모니터 이미지가 선명합니다."),
("skills","навыки","기술","Technical skills are essential.","Технические навыки необходимы.","기술적 능력이 필수적입니다."),
("software","программное обеспечение","소프트웨어","Install the latest software.","Установите последнюю версию программы.","최신 소프트웨어를 설치하세요."),
("storage","хранение, память","저장소","The device has plenty of storage.","У устройства много памяти.","장치에 저장 공간이 많습니다."),
("technical","технический","기술적인","Ask the technical support team.","Обратитесь в службу технической поддержки.","기술 지원 팀에 문의하세요."),
],
"Correspondence": [
("assemble","собирать, сшивать","모으다","Assemble the pages before mailing.","Соберите страницы перед отправкой.","발송 전에 페이지를 모으세요."),
("beforehand","заранее","사전에","Prepare the documents beforehand.","Подготовьте документы заранее.","문서를 사전에 준비하세요."),
("complicated","сложный","복잡한","The form is complicated to fill out.","Бланк сложно заполнить.","그 양식은 작성하기 복잡합니다."),
("courier","курьер","택배","Send the package by courier.","Отправьте посылку курьером.","소포를 택배로 보내세요."),
("express","срочный (о почте)","급행","Send it by express mail.","Отправьте срочной почтой.","급행 우편으로 보내세요."),
("fold","складывать","접다","Fold the letter neatly.","Аккуратно сложите письмо.","편지를 깔끔하게 접으세요."),
("layout","макет, расположение","레이아웃","Check the page layout.","Проверьте макет страницы.","페이지 레이아웃을 확인하세요."),
("mention","упоминать","언급하다","Please mention the reference number.","Пожалуйста, укажите номер ссылки.","참조 번호를 언급해 주세요."),
("petition","ходатайство, петиция","청원","They signed the petition.","Они подписали петицию.","그들은 청원에 서명했습니다."),
("proof","доказательство","증거","Keep the proof of delivery.","Сохраните доказательство доставки.","배송 증거를 보관하세요."),
("registered","заказной","등기의","Send it by registered mail.","Отправьте заказным письмом.","등기 우편으로 보내세요."),
("revise","пересматривать, исправлять","수정하다","Revise the draft before sending.","Исправьте черновик перед отправкой.","보내기 전에 초안을 수정하세요."),
],
"Job Advertising and Recruiting": [
("abundant","обильный, в большом количестве","풍부한","We received an abundant number of applications.","Мы получили большое количество заявок.","우리는 풍부한 지원서를 받았습니다."),
("accomplishment","достижение","성취","List your accomplishments on the resume.","Перечислите достижения в резюме.","이력서에 성취를 나열하세요."),
("bring together","объединять, собирать","모으다","The fair brings together employers and candidates.","Ярмарка объединяет работодателей и кандидатов.","박람회는 고용주와 지원자를 모읍니다."),
("candidate","кандидат","후보자","She is the best candidate for the job.","Она лучший кандидат на эту работу.","그녀는 그 직무에 최고의 후보자입니다."),
("come up with","придумать, предложить","생각해 내다","The team came up with a hiring plan.","Команда предложила план найма.","팀이 채용 계획을 생각해 냈습니다."),
("commensurate","соразмерный, соответствующий","상응하는","Salary is commensurate with experience.","Зарплата соразмерна опыту.","급여는 경력에 상응합니다."),
("match","соответствие, пара","일치","Your skills match the position.","Ваши навыки соответствуют должности.","당신의 기술이 그 직무와 일치합니다."),
("profile","профиль, характеристики","프로필","Update your online profile.","Обновите свой онлайн-профиль.","온라인 프로필을 업데이트하세요."),
("qualifications","квалификация, требования","자격","The job requires specific qualifications.","Работа требует определённой квалификации.","그 직무에는 특정 자격이 필요합니다."),
("recruit","нанимать, привлекать","채용하다","We need to recruit more staff.","Нам нужно нанять больше персонала.","더 많은 직원을 채용해야 합니다."),
("submit","подавать (заявку)","제출하다","Submit your application by Friday.","Подайте заявку до пятницы.","금요일까지 지원서를 제출하세요."),
("time-consuming","затратный по времени","시간이 많이 드는","Recruiting can be time-consuming.","Найм может быть затратным по времени.","채용은 시간이 많이 들 수 있습니다."),
],
"Applying and Interviewing": [
("ability","способность","능력","She has strong communication ability.","У неё сильные коммуникативные способности.","그녀는 의사소통 능력이 뛰어납니다."),
("apply","подавать заявку","지원하다","Apply online for the position.","Подайте заявку онлайн на должность.","온라인으로 그 직무에 지원하세요."),
("background","опыт, происхождение","배경","His background is in finance.","Его опыт связан с финансами.","그의 배경은 금융 분야입니다."),
("be ready for","быть готовым к","~에 준비되다","Be ready for the interview questions.","Будьте готовы к вопросам на собеседовании.","면접 질문에 준비하세요."),
("call in","приглашать (на собеседование)","불러들이다","They called in three candidates.","Они пригласили трёх кандидатов.","그들은 지원자 세 명을 불러들였습니다."),
("confidence","уверенность","자신감","Answer with confidence.","Отвечайте с уверенностью.","자신감 있게 답하세요."),
("constantly","постоянно","끊임없이","She constantly improves her skills.","Она постоянно совершенствует навыки.","그녀는 끊임없이 기술을 향상시킵니다."),
("expert","эксперт","전문가","He is an expert in his field.","Он эксперт в своей области.","그는 자신의 분야에서 전문가입니다."),
("follow up","доводить до конца, уточнять","후속 조치하다","Follow up with the employer after the interview.","Свяжитесь с работодателем после собеседования.","면접 후 고용주에게 후속 연락하세요."),
("hesitate","колебаться","주저하다","Do not hesitate to ask questions.","Не стесняйтесь задавать вопросы.","질문하는 것을 주저하지 마세요."),
("present","представлять, подавать","제시하다","Present your ideas clearly.","Чётко излагайте свои идеи.","자신의 생각을 명확히 제시하세요."),
("weakness","слабость","약점","Mention one weakness honestly.","Честно назовите одну слабость.","약점 하나를 정직하게 언급하세요."),
],
"Hiring and Training": [
("conduct","проводить","실시하다","Conduct training for new employees.","Проведите обучение для новых сотрудников.","신입 직원 교육을 실시하세요."),
("generate","создавать, производить","창출하다","The campaign generated new leads.","Кампания создала новые лиды.","캠페인이 새로운 잠재 고객을 창출했습니다."),
("hire","нанимать","고용하다","We plan to hire five new employees.","Мы планируем нанять пять новых сотрудников.","우리는 신입 직원 5명을 고용할 계획입니다."),
("keep up with","успевать за","~을 따라잡다","Keep up with the latest trends.","Успевайте за последними трендами.","최신 트렌드를 따라가세요."),
("look up to","уважать, брать пример","존경하다","New staff look up to their mentor.","Новички берут пример с наставника.","신입 직원들은 멘토를 존경합니다."),
("mentor","наставник","멘토","A mentor guides new employees.","Наставник направляет новых сотрудников.","멘토가 신입 직원을 지도합니다."),
("on track","по плану, в нужном направлении","계획대로","The training is on track.","Обучение идёт по плану.","교육이 계획대로 진행 중입니다."),
("reject","отклонять","거절하다","We rejected the unsuitable applicants.","Мы отклонили неподходящих кандидатов.","부적합한 지원자를 거절했습니다."),
("set up","налаживать, организовывать","설정하다","Set up a training program.","Организуйте программу обучения.","교육 프로그램을 설정하세요."),
("success","успех","성공","The program was a great success.","Программа имела большой успех.","그 프로그램은 큰 성공을 거두었습니다."),
("training","обучение","교육","Training improves performance.","Обучение повышает эффективность.","교육이 성과를 향상시킵니다."),
("update","обновлять","업데이트하다","Update the employee handbook.","Обновите справочник сотрудника.","직원 핸드북을 업데이트하세요."),
],
}
