# -*- coding: utf-8 -*-
# Part C: lessons 26-38
CATS_C = {
"Property and Departments": [
("adjacent","смежный, соседний","인접한","The two offices are adjacent.","Два офиса находятся рядом.","두 사무실은 인접해 있습니다."),
("collaboration","сотрудничество","협력","The departments work in collaboration.","Отделы работают в сотрудничестве.","부서들이 협력하여 일합니다."),
("concentrate","сосредоточиваться","집중하다","Concentrate on the renovation plan.","Сосредоточьтесь на плане ремонта.","리노베이션 계획에 집중하세요."),
("conducive","способствующий, благоприятный","도움이 되는","A quiet space is conducive to work.","Тихое место способствует работе.","조용한 공간은 업무에 도움이 됩니다."),
("disrupt","нарушать, срывать","방해하다","Construction disrupted the office.","Строительство нарушило работу офиса.","공사가 사무실 업무를 방해했습니다."),
("hamper","мешать, препятствовать","저해하다","Noise hampers productivity.","Шум мешает продуктивности.","소음이 생산성을 저해합니다."),
("inconsiderate","невнимательный к другим","배려 없는","Loud calls are inconsiderate.","Громкие звонки невнимательны к окружающим.","시끄러운 통화는 배려 없는 행동입니다."),
("lobby","вестибюль","로비","Wait for visitors in the lobby.","Ждите посетителей в вестибюле.","로비에서 방문객을 기다리세요."),
("move up","продвигаться, повышаться","올라가다","The team moved up to a larger floor.","Команда переехала на больший этаж.","팀이 더 넓은 층으로 올라갔습니다."),
("open to","открыт для, доступен","~에 열린","The area is open to employees.","Зона открыта для сотрудников.","그 공간은 직원들에게 열려 있습니다."),
("opt","выбирать, предпочитать","선택하다","They opted for a bigger office.","Они выбрали офис побольше.","그들은 더 큰 사무실을 선택했습니다."),
("scrutinize","тщательно изучать","면밀히 조사하다","Scrutinize the lease agreement.","Тщательно изучите договор аренды.","임대 계약을 면밀히 조사하세요."),
],
"Board Meeting and Committees": [
("adhere to","придерживаться","준수하다","All members must adhere to the rules.","Все члены должны придерживаться правил.","모든 위원은 규칙을 준수해야 합니다."),
("agenda","повестка дня","안건","The budget is first on the agenda.","Бюджет стоит первым в повестке дня.","예산이 안건의 첫 번째입니다."),
("bring up","поднимать (тему)","제기하다","She brought up the new proposal.","Она подняла новое предложение.","그녀가 새 제안을 제기했습니다."),
("conclude","завершать","결론을 내리다","The committee concluded the meeting.","Комитет завершил собрание.","위원회가 회의를 마쳤습니다."),
("go ahead","получить добро, разрешение","진행 승인","The board gave the go ahead for the project.","Совет дал добро на проект.","이사회가 프로젝트 진행을 승인했습니다."),
("goal","цель","목표","Our main goal is to cut costs.","Наша главная цель — сократить расходы.","우리의 주요 목표는 비용 절감입니다."),
("lengthy","длительный","장황한","The report was too lengthy to read.","Отчёт был слишком длинным.","보고서가 너무 장황했습니다."),
("matter","вопрос, дело","문제","This is an important matter to discuss.","Это важный вопрос для обсуждения.","이것은 논의할 중요한 문제입니다."),
("periodically","периодически","주기적으로","The group meets periodically.","Группа собирается периодически.","그룹은 주기적으로 모입니다."),
("priority","приоритет","우선순위","Safety is our top priority.","Безопасность — наш главный приоритет.","안전이 최우선 순위입니다."),
("progress","продвижение, прогресс","진행 상황","The committee reviewed the project's progress.","Комитет рассмотрел ход проекта.","위원회가 프로젝트 진행 상황을 검토했습니다."),
("waste","трата, пустая трата","낭비","Meetings should not waste time.","Собрания не должны тратить время.","회의는 시간을 낭비해서는 안 됩니다."),
],
"Quality Control": [
("brand","бренд","브랜드","Consumers trust the brand.","Потребители доверяют бренду.","소비자가 그 브랜드를 신뢰합니다."),
("conform","соответствовать","준수하다","Every product must conform to the standard.","Каждый продукт должен соответствовать стандарту.","모든 제품이 표준을 준수해야 합니다."),
("defect","дефект","결함","The part was rejected because of a defect.","Деталь была отклонена из-за дефекта.","결함 때문에 부품이 반려되었습니다."),
("enhance","улучшать","향상시키다","New materials enhance quality.","Новые материалы улучшают качество.","새로운 소재가 품질을 향상시킵니다."),
("garment","предмет одежды","의류","Each garment is checked before shipping.","Каждая вещь проверяется перед отправкой.","각 의류는 출고 전에 검사됩니다."),
("inspect","проверять","검사하다","Workers inspect every batch.","Рабочие проверяют каждую партию.","근로자가 모든 배치를 검사합니다."),
("perceive","воспринимать","인지하다","Customers perceive the product as reliable.","Потребители считают продукт надёжным.","고객은 그 제품을 신뢰할 수 있다고 인지합니다."),
("repel","отталкивать","밀어내다","The coating repels water.","Покрытие отталкивает воду.","코팅이 물을 밀어냅니다."),
("take back","принимать обратно","반품받다","The store will take back defective items.","Магазин примет обратно бракованные товары.","매장이 불량품을 반품받을 것입니다."),
("throw out","выбрасывать","버리다","Damaged goods are thrown out.","Повреждённые товары выбрасываются.","손상된 상품은 버려집니다."),
("uniform","единообразный","균일한","The boxes have a uniform size.","Коробки имеют единообразный размер.","상자 크기가 균일합니다."),
("wrinkle","складка, морщина","주름","The fabric does not wrinkle easily.","Ткань легко не мнётся.","이 원단은 쉽게 주름지지 않습니다."),
],
"Product Development": [
("anxious","обеспокоенный","불안한","The team was anxious about the launch.","Команда беспокоилась о запуске.","팀이 출시에 대해 불안해했습니다."),
("ascertain","устанавливать, выяснять","확인하다","Ascertain whether the product is safe.","Установите, безопасен ли продукт.","제품이 안전한지 확인하세요."),
("assume","предполагать","가정하다","Do not assume the market is ready.","Не предполагайте, что рынок готов.","시장이 준비되었다고 가정하지 마세요."),
("decade","десятилетие","10년","The product took a decade to develop.","На разработку продукта ушло десятилетие.","그 제품은 개발에 10년이 걸렸습니다."),
("examine","изучать, осматривать","조사하다","Examine the product from every aspect.","Изучите продукт со всех сторон.","제품을 모든 측면에서 조사하세요."),
("experiment","экспериментировать","실험하다","Researchers experiment with new designs.","Исследователи экспериментируют с новыми дизайнами.","연구자들이 새로운 디자인을 실험합니다."),
("logical","логичный","논리적인","The design follows a logical process.","Дизайн следует логичному процессу.","설계는 논리적인 과정을 따릅니다."),
("research","исследование","연구","They conduct market research.","Они проводят исследование рынка.","그들은 시장 조사를 실시합니다."),
("responsibility","ответственность","책임","Product safety is our responsibility.","Безопасность продукта — наша ответственность.","제품 안전은 우리의 책임입니다."),
("solve","решать","해결하다","Solve the design problem quickly.","Быстро решите проблему дизайна.","설계 문제를 빨리 해결하세요."),
("supervisor","руководитель, супервизор","관리자","The supervisor leads the team.","Руководитель возглавляет команду.","관리자가 팀을 이끕니다."),
("systematic","систематический","체계적인","Use a systematic approach.","Используйте систематический подход.","체계적인 접근 방식을 사용하세요."),
],
"Renting and Leasing": [
("apprehensive","опасающийся, встревоженный","염려하는","Tenants were apprehensive about the cost.","Арендаторы опасались расходов.","임차인들이 비용을 염려했습니다."),
("circumstance","обстоятельство","상황","The circumstances changed quickly.","Обстоятельства быстро изменились.","상황이 빠르게 변했습니다."),
("condition","состояние, условие","상태","The building is in good condition.","Здание в хорошем состоянии.","건물 상태가 좋습니다."),
("due to","из-за, вследствие","~ 때문에","Rent rose due to high demand.","Аренда выросла из-за высокого спроса.","수요가 높아 임대료가 올랐습니다."),
("fluctuate","колебаться","변동하다","Rent prices fluctuate by season.","Цены на аренду колеблются по сезонам.","임대료가 계절에 따라 변동합니다."),
("get out of","выходить из (договора)","~에서 벗어나다","They wanted to get out of the lease.","Они хотели выйти из договора аренды.","그들은 임대 계약에서 벗어나고 싶어 했습니다."),
("indicator","показатель, индикатор","지표","Vacancy is an indicator of demand.","Свободные площади — показатель спроса.","공실률은 수요의 지표입니다."),
("lease","арендовать, сдавать в аренду","임대하다","They lease the office for five years.","Они арендуют офис на пять лет.","그들은 사무실을 5년간 임대합니다."),
("lock into","зафиксировать, закрепить","고정하다","We locked into a long-term rate.","Мы зафиксировали долгосрочную ставку.","우리는 장기 요율을 고정했습니다."),
("occupancy","занятость, заполняемость","입주율","The building has high occupancy.","У здания высокая заполняемость.","건물 입주율이 높습니다."),
("option","вариант, возможность","선택권","We have the option to renew.","У нас есть возможность продления.","우리에게는 갱신 선택권이 있습니다."),
("subject to","при условии, с учётом","~에 따라","The rent is subject to change.","Арендная плата может измениться.","임대료는 변동될 수 있습니다."),
],
"Selecting a Restaurant": [
("appeal","привлекательность","매력","The menu has great appeal.","У меню большая привлекательность.","그 메뉴는 매력이 큽니다."),
("arrive","прибывать","도착하다","The food arrived quickly.","Еда прибыла быстро.","음식이 빨리 도착했습니다."),
("compromise","компромисс","타협","They made a compromise on the choice.","Они пошли на компромисс в выборе.","그들은 선택에 대해 타협했습니다."),
("daring","смелый","대담한","Ordering that dish was a daring choice.","Заказать то блюдо было смелым выбором.","그 요리를 주문한 것은 대담한 선택이었습니다."),
("familiar","знакомый","익숙한","The dishes were familiar to everyone.","Блюда были знакомы всем.","그 요리는 모두에게 익숙했습니다."),
("guide","гид, путеводитель","안내","We used the guide to pick a restaurant.","Мы воспользовались путеводителем, чтобы выбрать ресторан.","우리는 식당을 고르기 위해 안내서를 이용했습니다."),
("majority","большинство","대부분","The majority chose the café.","Большинство выбрало кафе.","대부분이 카페를 선택했습니다."),
("mix","смешивать","섞다","The chef mixed unusual ingredients.","Шеф-повар смешал необычные ингредиенты.","셰프가 특이한 재료를 섞었습니다."),
("rely","полагаться","의지하다","I rely on the reviews to choose.","Я полагаюсь на отзывы при выборе.","나는 선택할 때 리뷰에 의지합니다."),
("secure","получать, обеспечивать","확보하다","We secured a table by the window.","Мы обеспечили себе столик у окна.","우리는 창가 자리를 확보했습니다."),
("subjective","субъективный","주관적인","Taste in food is subjective.","Вкус в еде субъективен.","음식 취향은 주관적입니다."),
("suggest","предлагать","제안하다","She suggested a good café.","Она предложила хорошее кафе.","그녀가 좋은 카페를 제안했습니다."),
],
"Eating Out": [
("basic","основной, базовый","기본적인","The restaurant serves basic dishes.","Ресторан подаёт простые блюда.","그 식당은 기본적인 요리를 제공합니다."),
("complete","завершать","완료하다","Complete your order at the counter.","Завершите заказ у стойки.","카운터에서 주문을 완료하세요."),
("excite","волновать, возбуждать","흥미를 돋우다","The new menu excited customers.","Новое меню взволновало клиентов.","새 메뉴가 고객의 흥미를 돋웠습니다."),
("flavor","вкус, аромат","맛","The dish has a rich flavor.","У блюда насыщенный вкус.","그 요리는 풍부한 맛이 있습니다."),
("forget","забывать","잊다","Do not forget to leave a tip.","Не забудьте оставить чаевые.","팁을 두는 것을 잊지 마세요."),
("ingredient","ингредиент","재료","The chef uses fresh ingredients.","Шеф-повар использует свежие ингредиенты.","셰프가 신선한 재료를 사용합니다."),
("judge","судить, оценивать","판단하다","Judge the restaurant by its service.","Оцените ресторан по сервису.","서비스로 식당을 판단하세요."),
("mix-up","путаница","혼동","There was a mix-up with the order.","Произошла путаница с заказом.","주문에 혼동이 있었습니다."),
("patron","посетитель, клиент","단골","The patron visits every week.","Этот посетитель приходит каждую неделю.","그 단골은 매주 방문합니다."),
("predict","предсказывать","예측하다","They predict a busy weekend.","Они предсказывают оживлённые выходные.","그들은 바쁜 주말을 예측합니다."),
("random","случайный","무작위의","They surveyed a random sample of guests.","Они опросили случайную выборку гостей.","그들은 무작위 고객 표본을 조사했습니다."),
("remind","напоминать","상기시키다","Remind the staff about the reservation.","Напомните персоналу о бронировании.","직원에게 예약을 상기시키세요."),
],
"Ordering Lunch": [
("burdensome","обременительный","부담스러운","Processing lunch orders is burdensome.","Обработка заказов на обед обременительна.","점심 주문 처리는 부담스럽습니다."),
("common","общий, распространённый","흔한","A sandwich is a common lunch choice.","Сэндвич — распространённый выбор на обед.","샌드위치는 흔한 점심 선택입니다."),
("delivery","доставка","배달","The restaurant offers delivery.","Ресторан предлагает доставку.","그 식당은 배달을 제공합니다."),
("elegant","элегантный, изысканный","우아한","The restaurant has an elegant dining room.","У ресторана элегантный обеденный зал.","그 식당은 우아한 식당 공간이 있습니다."),
("fall to","доставаться, ложиться на","~에게 돌아가다","The task fell to the new assistant.","Задача досталась новому помощнику.","그 일은 새 조수에게 돌아갔습니다."),
("impress","впечатлять","감명을 주다","The service impressed the clients.","Сервис впечатлил клиентов.","서비스가 고객에게 감명을 주었습니다."),
("individual","отдельный, индивидуальный","개인의","Each individual order is tracked.","Каждый отдельный заказ отслеживается.","각 개인 주문이 추적됩니다."),
("list","список","목록","Check the lunch menu list.","Проверьте список обеденного меню.","점심 메뉴 목록을 확인하세요."),
("multiple","несколько, множественный","여러 개의","We received multiple orders.","Мы получили несколько заказов.","우리는 여러 주문을 받았습니다."),
("narrow","узкий, ограниченный","좁은","The menu choices are narrow.","Выбор блюд ограничен.","메뉴 선택이 좁습니다."),
("pick up","забирать (еду навынос)","픽업하다","Pick up your lunch at noon.","Заберите обед в полдень.","정오에 점심을 픽업하세요."),
("settle","улаживать, решать","해결하다","Settle the bill after lunch.","Оплатите счёт после обеда.","점심 후에 계산을 해결하세요."),
],
"Cooking as a Career": [
("accustom to","привыкать к","~에 익숙해지다","Chefs accustom themselves to long hours.","Шеф-повара привыкают к долгим часам.","셰프들은 긴 근무 시간에 익숙해집니다."),
("apprentice","ученик, подмастерье","견습생","He worked as an apprentice in a kitchen.","Он работал подмастерьем на кухне.","그는 주방에서 견습생으로 일했습니다."),
("culinary","кулинарный","요리의","She studied culinary arts.","Она изучала кулинарное искусство.","그녀는 요리 예술을 공부했습니다."),
("demanding","требовательный, напряжённый","힘든","The job is physically demanding.","Работа физически тяжёлая.","그 일은 육체적으로 힘듭니다."),
("draw","привлекать","끌어들이다","The chef drew many customers.","Шеф-повар привлёк много клиентов.","셰프가 많은 고객을 끌어들였습니다."),
("incorporate","включать, вносить","통합하다","She incorporated new ideas into the menu.","Она включила новые идеи в меню.","그녀는 새 아이디어를 메뉴에 통합했습니다."),
("influx","приток","유입","There was an influx of new chefs.","Был приток новых шеф-поваров.","새 셰프들이 유입되었습니다."),
("method","метод","방법","He developed a new cooking method.","Он разработал новый метод приготовления.","그는 새로운 조리 방법을 개발했습니다."),
("outlet","выход, отдушина","배출구","Cooking is an outlet for creativity.","Готовка — выход для творчества.","요리는 창의성의 배출구입니다."),
("profession","профессия","직업","Cooking is a respected profession.","Готовка — уважаемая профессия.","요리는 존경받는 직업입니다."),
("relinquish","отказываться, уступать","포기하다","He refused to relinquish control of the kitchen.","Он отказался уступать контроль над кухней.","그는 주방 통제를 포기하지 않았습니다."),
("theme","тема","주제","The party had a tropical theme.","Вечеринка была в тропической теме.","파티는 열대 주제로 진행되었습니다."),
],
"Events": [
("assist","помогать, ассистировать","돕다","Volunteers assist at the event.","Волонтёры помогают на мероприятии.","자원봉사자들이 행사에서 돕습니다."),
("coordinate","координировать","조정하다","Coordinate the event schedule.","Скоординируйте расписание мероприятия.","행사 일정을 조정하세요."),
("dimension","измерение, масштаб","규모","The event added a new dimension to marketing.","Мероприятие добавило новое измерение маркетингу.","행사가 마케팅에 새로운 규모를 더했습니다."),
("exact","точный","정확한","We need the exact number of guests.","Нам нужно точное число гостей.","정확한 게스트 수가 필요합니다."),
("general","общий","일반적인","The general plan is ready.","Общий план готов.","일반적인 계획이 준비되었습니다."),
("ideal","идеальный","이상적인","This venue is ideal for the event.","Это место идеально для мероприятия.","이 장소는 행사에 이상적입니다."),
("lead time","срок подготовки","준비 기간","Plan with enough lead time.","Планируйте с достаточным запасом времени.","충분한 준비 기간을 두고 계획하세요."),
("plan","план","계획","Finalize the event plan.","Завершите план мероприятия.","행사 계획을 확정하세요."),
("proximity","близость","근접성","The venue's proximity to hotels matters.","Близость площадки к отелям важна.","장소와 호텔의 근접성이 중요합니다."),
("regulation","правило, норма","규정","Follow safety regulations.","Соблюдайте правила безопасности.","안전 규정을 따르세요."),
("site","площадка, место","장소","Choose a suitable site.","Выберите подходящую площадку.","적합한 장소를 선택하세요."),
("stage","сцена, этап","무대","The stage is set for the ceremony.","Сцена готова к церемонии.","행사를 위한 무대가 준비되었습니다."),
],
"General Travel": [
("agency","агентство","여행사","Book through a travel agency.","Бронируйте через туристическое агентство.","여행사를 통해 예약하세요."),
("announcement","объявление","안내 방송","Listen to the departure announcement.","Слушайте объявление об отправлении.","출발 안내 방송을 들으세요."),
("beverage","напиток","음료","Beverages are served on the flight.","Напитки подаются на борту.","기내에서 음료가 제공됩니다."),
("blanket","одеяло","담요","Ask for a blanket on the plane.","Попросите одеяло в самолёте.","비행기에서 담요를 요청하세요."),
("board","садиться на борт","탑승하다","Passengers board the plane now.","Пассажиры садятся на борт.","승객들이 지금 탑승합니다."),
("claim","требовать, получать (багаж)","찾다","Claim your baggage at the carousel.","Получите багаж у ленты.","수하물 수취대에서 짐을 찾으세요."),
("delay","задержка","지연","The flight has a two-hour delay.","Рейс задержан на два часа.","항공편이 2시간 지연되었습니다."),
("depart","отправляться","출발하다","The train departs at noon.","Поезд отправляется в полдень.","기차가 정오에 출발합니다."),
("embark","отправляться (в путешествие)","시작하다","They embarked on a long trip.","Они отправились в долгое путешествие.","그들은 긴 여행을 시작했습니다."),
("itinerary","маршрут","여행 일정","Check the travel itinerary.","Проверьте маршрут поездки.","여행 일정을 확인하세요."),
("prohibit","запрещать","금지하다","Smoking is prohibited on board.","Курение запрещено на борту.","기내 흡연은 금지됩니다."),
("valid","действительный","유효한","Your passport must be valid.","Ваш паспорт должен быть действительным.","여권이 유효해야 합니다."),
],
"Airlines": [
("deal with","иметь дело с, справляться","대처하다","The staff deal with complaints daily.","Персонал ежедневно разбирает жалобы.","직원들이 매일 불만에 대처합니다."),
("destination","пункт назначения","목적지","Our destination is Seoul.","Наш пункт назначения — Сеул.","우리의 목적지는 서울입니다."),
("distinguish","различать, отличать","구별하다","Distinguish between the two terminals.","Различайте два терминала.","두 터미널을 구별하세요."),
("economical","экономичный","경제적인","Economy class is economical.","Эконом-класс экономичен.","이코노미 클래스는 경제적입니다."),
("equivalent","эквивалент, равноценный","동등한","The fare is equivalent to a train ticket.","Цена сопоставима с билетом на поезд.","요금이 기차표와 동등합니다."),
("excursion","экскурсия, поездка","여행","We took a short excursion.","Мы совершили короткую экскурсию.","우리는 짧은 여행을 했습니다."),
("expensive","дорогой","비싼","First-class tickets are expensive.","Билеты первого класса дорогие.","일등석 표는 비쌉니다."),
("extend","продлевать","연장하다","Extend your stay by two days.","Продлите пребывание на два дня.","체류를 이틀 연장하세요."),
("prospective","потенциальный, будущий","예비의","A prospective passenger called.","Позвонил потенциальный пассажир.","예비 승객이 전화했습니다."),
("situation","ситуация","상황","The weather situation improved.","Ситуация с погодой улучшилась.","날씨 상황이 개선되었습니다."),
("substantial","значительный","상당한","The delay caused substantial cost.","Задержка повлекла значительные расходы.","지연이 상당한 비용을 초래했습니다."),
("system","система","시스템","The booking system is down.","Система бронирования не работает.","예약 시스템이 다운되었습니다."),
],
"Trains": [
("comprehensive","всесторонний, полный","포괄적인","The rail network is comprehensive.","Железнодорожная сеть обширна.","철도망이 포괄적입니다."),
("deluxe","люкс, высшего класса","디럭스","They booked a deluxe cabin.","Они забронировали люкс-купе.","그들은 디럭스 객실을 예약했습니다."),
("directory","справочник","안내","Check the station directory.","Проверьте справочник вокзала.","역 안내를 확인하세요."),
("duration","продолжительность","소요 시간","The journey's duration is four hours.","Продолжительность поездки — четыре часа.","여행 소요 시간은 4시간입니다."),
("entitle","давать право","자격을 주다","The pass entitles you to a discount.","Пропуск даёт право на скидку.","패스가 할인 자격을 부여합니다."),
("fare","плата за проезд","운임","The train fare is reasonable.","Плата за проезд разумная.","기차 운임이 합리적입니다."),
("offset","компенсировать","상쇄하다","Lower fares offset the slower trip.","Низкие тарифы компенсируют медленную поездку.","낮은 운임이 느린 여행을 상쇄합니다."),
("operate","эксплуатировать, работать","운행하다","Trains operate every hour.","Поезда ходят каждый час.","기차가 매시간 운행합니다."),
("punctual","пунктуальный","정시의","The train is always punctual.","Поезд всегда пунктуален.","그 기차는 항상 정시입니다."),
("relatively","относительно","비교적","The trip was relatively cheap.","Поездка была относительно дешёвой.","여행이 비교적 저렴했습니다."),
("remainder","остаток","나머지","Spend the remainder of the trip resting.","Проведите остаток поездки отдыхая.","남은 여정 동안 쉬세요."),
("remote","отдалённый","외딴","The station is in a remote area.","Станция находится в отдалённом районе.","역이 외딴 지역에 있습니다."),
],
"Hotels": [
("advance","заранее","사전에","Book your room in advance.","Забронируйте номер заранее.","객실을 사전에 예약하세요."),
("chain","сеть (отелей)","체인","The hotel is part of a chain.","Отель входит в сеть.","그 호텔은 체인의 일부입니다."),
("check in","зарегистрироваться, заселиться","체크인하다","Check in after 3 PM.","Заселяйтесь после 15:00.","오후 3시 이후에 체크인하세요."),
("confirm","подтверждать","확인하다","Confirm your reservation by email.","Подтвердите бронирование по электронной почте.","이메일로 예약을 확인하세요."),
("expect","ожидать","기대하다","Guests expect clean rooms.","Гости ожидают чистые номера.","고객은 깨끗한 객실을 기대합니다."),
("housekeeper","горничная","하우스키퍼","The housekeeper cleans the rooms.","Горничная убирает номера.","하우스키퍼가 객실을 청소합니다."),
("notify","уведомлять","알리다","Notify the front desk of any issue.","Сообщайте о проблемах на стойку регистрации.","문제가 있으면 프런트에 알리세요."),
("preclude","исключать, препятствовать","막다","The renovation may preclude booking.","Ремонт может помешать бронированию.","리노베이션이 예약을 막을 수 있습니다."),
("quote","называть цену","견적을 내다","The clerk quoted the nightly rate.","Сотрудник назвал цену за ночь.","직원이 1박 요금을 견적했습니다."),
("rate","тариф","요금","The weekend rate is higher.","Тариф в выходные выше.","주말 요금이 더 높습니다."),
("reserve","бронировать, резервировать","예약하다","Reserve a room for two nights.","Забронируйте номер на две ночи.","2박 객실을 예약하세요."),
("service","обслуживание, сервис","서비스","The hotel offers room service.","Отель предлагает обслуживание номеров.","호텔이 룸서비스를 제공합니다."),
],
}
