#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bring affected TOEIC categories to the EXACT 12 words per lesson from
Lin Lougheed, "600 Essential Words for the TOEIC" (Barron's).

Category -> lesson mapping verified against the book's Table of Contents.
Word lists verified against the book's Word Index and per-lesson sources.

Updates root words_optimized.json AND public/words_optimized.json.
"""
import json
from collections import Counter

SRC = 'words_optimized.json'

def slug(s):
    return s.lower().replace(' ', '-')

def card(cat, eng, rus, kor, exEng, exRus, exKor):
    return {
        'id': f'{slug(cat)}--{slug(eng)}',
        'category': cat,
        'eng': eng,
        'rus': rus,
        'correct': rus,
        'exampleEng': exEng,
        'exampleRus': exRus,
        'kor': kor,
        'exampleKor': exKor,
    }

# (eng, rus, kor, exampleEng, exampleRus, exampleKor)
BOOK = {
    'Board Meeting and Committees': [
        ('adhere to','придерживаться','준수하다',
         'All members must adhere to the meeting rules.','Все члены должны придерживаться правил собрания.','모든 위원은 회의 규칙을 준수해야 합니다.'),
        ('agenda','повестка дня','안건',
         'The budget is first on the agenda.','Бюджет стоит первым в повестке дня.','예산이 안건의 첫 번째입니다.'),
        ('bring up','поднимать (тему)','제기하다',
         'She brought up the new proposal at the meeting.','Она подняла новое предложение на собрании.','그녀는 회의에서 새 제안을 제기했습니다.'),
        ('conclude','завершать','결론을 내리다',
         'The committee concluded the meeting on time.','Комитет завершил собрание вовремя.','위원회가 회의를 제시간에 마쳤습니다.'),
        ('go ahead','получить добро','진행하다',
         'The board gave the go ahead for the project.','Совет дал добро на проект.','이사회가 프로젝트 진행을 승인했습니다.'),
        ('goal','цель','목표',
         'Our main goal is to cut costs.','Наша главная цель — сократить расходы.','우리의 주요 목표는 비용을 줄이는 것입니다.'),
        ('lengthy','длительный','장황한',
         'The report was too lengthy to read.','Отчёт был слишком длинным, чтобы его прочитать.','보고서가 너무 장황해서 읽을 수 없었습니다.'),
        ('matter','вопрос','문제',
         'This is an important matter to discuss.','Это важный вопрос для обсуждения.','이것은 논의할 중요한 문제입니다.'),
        ('periodically','периодически','주기적으로',
         'The group meets periodically.','Группа собирается периодически.','그룹은 주기적으로 모입니다.'),
        ('priority','приоритет','우선순위',
         'Safety is our top priority.','Безопасность — наш главный приоритет.','안전이 최우선 순위입니다.'),
        ('progress','продвижение','진행',
         'The committee reviewed the project\'s progress.','Комитет рассмотрел продвижение проекта.','위원회가 프로젝트 진행 상황을 검토했습니다.'),
        ('waste','трата','낭비',
         'Meetings should not waste people\'s time.','Собрания не должны тратить время людей.','회의는 사람들의 시간을 낭비해서는 안 됩니다.'),
    ],
    'Quality Control': [
        ('brand','бренд','브랜드',
         'Consumers trust the brand.','Потребители доверяют бренду.','소비자가 그 브랜드를 신뢰합니다.'),
        ('conform','соответствовать','준수하다',
         'Every product must conform to the standard.','Каждый продукт должен соответствовать стандарту.','모든 제품이 표준을 준수해야 합니다.'),
        ('defect','дефект','결함',
         'The part was rejected because of a defect.','Деталь была отклонена из-за дефекта.','결함 때문에 부품이 반려되었습니다.'),
        ('enhance','улучшать','향상시키다',
         'New materials enhance product quality.','Новые материалы улучшают качество продукции.','새로운 소재가 제품 품질을 향상시킵니다.'),
        ('garment','предмет одежды','의류',
         'Each garment is checked before shipping.','Каждый предмет одежды проверяется перед отправкой.','각 의류는 출고 전에 검사됩니다.'),
        ('inspect','проверять','검사하다',
         'Workers inspect every batch.','Рабочие проверяют каждую партию.','근로자가 모든 배치를 검사합니다.'),
        ('perceive','воспринимать','인지하다',
         'Customers perceive the product as reliable.','Потребители воспринимают продукт как надёжный.','고객은 그 제품을 신뢰할 수 있는 것으로 인지합니다.'),
        ('repel','отталкивать','방어하다',
         'The coating repels water.','Покрытие отталкивает воду.','코팅이 물을 방어합니다.'),
        ('take back','принимать обратно','반품하다',
         'The store will take back defective items.','Магазин примет обратно бракованные товары.','매장이 불량품을 반품 받을 것입니다.'),
        ('throw out','выбрасывать','버리다',
         'Damaged goods are thrown out.','Повреждённые товары выбрасываются.','손상된 상품은 버려집니다.'),
        ('uniform','единообразный','균일한',
         'The boxes have a uniform size.','Коробки имеют единообразный размер.','상자 크기가 균일합니다.'),
        ('wrinkle','морщина','주름',
         'The fabric does not wrinkle easily.','Ткань легко не мнётся.','이 원단은 쉽게 주름지지 않습니다.'),
    ],
    'Selecting a Restaurant': [
        ('appeal','привлекательность','매력',
         'The menu has great appeal.','У меню большая привлекательность.','그 메뉴는 매력이 큽니다.'),
        ('arrive','прибывать','도착하다',
         'The food arrived quickly.','Еда прибыла быстро.','음식이 빨리 도착했습니다.'),
        ('compromise','компромисс','타협',
         'They made a compromise on the choice of restaurant.','Они пошли на компромисс в выборе ресторана.','그들은 식당 선택에 대해 타협했습니다.'),
        ('daring','смелый','대담한',
         'Ordering that dish was a daring choice.','Заказать то блюдо было смелым выбором.','그 요리를 주문한 것은 대담한 선택이었습니다.'),
        ('familiar','знакомый','익숙한',
         'The dishes were familiar to everyone.','Блюда были знакомы всем.','그 요리는 모두에게 익숙했습니다.'),
        ('guide','гид, путеводитель','안내',
         'We used the guide to pick a restaurant.','Мы воспользовались путеводителем, чтобы выбрать ресторан.','우리는 식당을 고르기 위해 안내서를 이용했습니다.'),
        ('majority','большинство','대부분',
         'The majority chose the café.','Большинство выбрало кафе.','대부분이 카페를 선택했습니다.'),
        ('mix','смешивать','섞다',
         'The chef mixed unusual ingredients.','Шеф-повар смешал необычные ингредиенты.','셰프가 특이한 재료를 섞었습니다.'),
        ('rely','полагаться','의지하다',
         'I rely on the reviews to choose.','Я полагаюсь на отзывы при выборе.','나는 선택할 때 리뷰에 의지합니다.'),
        ('secure','получать, обеспечивать','확보하다',
         'We secured a table by the window.','Мы обеспечили себе столик у окна.','우리는 창가 자리를 확보했습니다.'),
        ('subjective','субъективный','주관적인',
         'Taste in food is subjective.','Вкус в еде субъективен.','음식 취향은 주관적입니다.'),
        ('suggestion','предложение','제안',
         'She gave a suggestion for a good café.','Она дала предложение насчёт хорошего кафе.','그녀가 좋은 카페를 제안했습니다.'),
    ],
    'Cooking as a Career': [
        ('accustom to','привыкать к','익숙해지다',
         'Chefs accustom themselves to long hours.','Шеф-повара привыкают к долгим часам работы.','셰프들은 긴 근무 시간에 익숙해집니다.'),
        ('apprentice','ученик, подмастерье','견습생',
         'He worked as an apprentice in a kitchen.','Он работал подмастерьем на кухне.','그는 주방에서 견습생으로 일했습니다.'),
        ('culinary','кулинарный','요리의',
         'She studied culinary arts.','Она изучала кулинарное искусство.','그녀는 요리 예술을 공부했습니다.'),
        ('demand','требовать','요구하다',
         'The job demands many hours.','Работа требует много времени.','그 일은 많은 시간을 요구합니다.'),
        ('draw','привлекать','끌어들이다',
         'The chef drew many customers.','Шеф-повар привлёк много клиентов.','셰프가 많은 고객을 끌어들였습니다.'),
        ('incorporate','включать','통합하다',
         'She incorporated new ideas into the menu.','Она включила новые идеи в меню.','그녀는 새 아이디어를 메뉴에 통합했습니다.'),
        ('influx','приток','유입',
         'There was an influx of new chefs.','Был приток новых шеф-поваров.','새 셰프들이 유입되었습니다.'),
        ('method','метод','방법',
         'He developed a new cooking method.','Он разработал новый метод приготовления.','그는 새로운 조리 방법을 개발했습니다.'),
        ('outlet','выход, отдушина','배출구',
         'Cooking is an outlet for creativity.','Готовка — выход для творчества.','요리는 창의성의 배출구입니다.'),
        ('profession','профессия','직업',
         'Cooking is a respected profession.','Готовка — уважаемая профессия.','요리는 존경받는 직업입니다.'),
        ('relinquish','отказываться','포기하다',
         'He refused to relinquish control of the kitchen.','Он отказался уступать контроль над кухней.','그는 주방에 대한 통제를 포기하지 않았습니다.'),
        ('theme','тема','주제',
         'The party had a tropical theme.','Вечеринка была в тропической теме.','파티는 열대 주제로 진행되었습니다.'),
    ],
    'Car Rentals': [
        ('busy','занятой','바쁜',
         'The rental office was busy all day.','Офис проката был занят весь день.','렌탈 사무실은 하루 종일 바빴습니다.'),
        ('coincide','совпадать','일치하다',
         'My trip coincided with the holiday.','Моя поездка совпала с праздником.','내 여행이 휴일과 일치했습니다.'),
        ('confusion','путаница','혼란',
         'There was confusion about the pickup time.','Была путаница со временем получения машины.','픽업 시간에 혼란이 있었습니다.'),
        ('contact','связываться','연락하다',
         'Contact the office to reserve a car.','Свяжитесь с офисом, чтобы забронировать машину.','차를 예약하려면 사무실에 연락하세요.'),
        ('disappoint','разочаровывать','실망시키다',
         'The service did not disappoint us.','Сервис нас не разочаровал.','서비스는 우리를 실망시키지 않았습니다.'),
        ('intend','намереваться','의도하다',
         'I intend to rent a car for the weekend.','Я намереваюсь арендовать машину на выходные.','나는 주말에 차를 빌릴 의도입니다.'),
        ('license','права, лицензия','면허',
         'You need a valid license to rent.','Для аренды нужны действующие права.','렌탈에는 유효한 면허가 필요합니다.'),
        ('nervous','нервный','긴장한',
         'He was nervous about driving in traffic.','Он нервничал из-за вождения в потоке.','그는 교통 속에서 운전하는 것이 긴장되었습니다.'),
        ('optional','необязательный','선택 사항인',
         'Insurance is optional for renters.','Страховка для арендаторов необязательна.','보험은 렌터 이용자에게 선택 사항입니다.'),
        ('tempt','соблазнять','유혹하다',
         'The offer tempted me to rent a larger car.','Предложение соблазнило меня арендовать машину побольше.','그 제안이 더 큰 차를 빌리도록 유혹했습니다.'),
        ('thrill','волнение','스릴',
         'Driving along the coast was a thrill.','Езда вдоль побережья была настоящим волнением.','해안을 따라 운전하는 것은 스릴이었습니다.'),
        ('tier','уровень, класс','등급',
         'They rent cars at every tier.','Они сдают машины любого класса.','그들은 모든 등급의 차를 렌트합니다.'),
    ],
    'Movies': [
        ('attain','достигать','달성하다',
         'The film attained great popularity.','Фильм достиг большой популярности.','그 영화는 큰 인기를 달성했습니다.'),
        ('combine','объединять','결합하다',
         'The movie combines drama and comedy.','Фильм объединяет драму и комедию.','그 영화는 드라마와 코미디를 결합합니다.'),
        ('continue','продолжать','계속하다',
         'The series continued for years.','Сериал продолжался годами.','시리즈는 몇 년 동안 계속되었습니다.'),
        ('description','описание','묘사',
         'The description matches the plot.','Описание соответствует сюжету.','묘사가 줄거리와 일치합니다.'),
        ('disperse','рассеиваться','흩어지다',
         'The crowd dispersed after the show.','Толпа рассеялась после шоу.','공연 후 군중이 흩어졌습니다.'),
        ('entertainment','развлечение','오락',
         'The film is pure entertainment.','Фильм — чистое развлечение.','그 영화는 순수한 오락입니다.'),
        ('influence','влияние','영향',
         'The director influenced many filmmakers.','Режиссёр повлиял на многих кинематографистов.','그 감독은 많은 영화 제작자에게 영향을 미쳤습니다.'),
        ('range','диапазон','범위',
         'The movie appeals to a wide range of viewers.','Фильм привлекает широкий круг зрителей.','그 영화는 다양한 관객층에게 어필합니다.'),
        ('release','выпускать, премьера','개봉하다',
         'The studio released the film on Friday.','Студия выпустила фильм в пятницу.','스튜디오가 금요일에 그 영화를 개봉했습니다.'),
        ('represent','представлять','나타내다',
         'The film represents a new trend.','Фильм представляет новый тренд.','그 영화는 새로운 경향을 나타냅니다.'),
        ('separate','отделять','분리하다',
         'The episodes are separate stories.','Эпизоды — отдельные истории.','에피소드는 별개의 이야기입니다.'),
        ('successive','последовательный','연속적인',
         'The movie was a hit for three successive weeks.','Фильм был хитом три недели подряд.','그 영화는 3주 연속 히트였습니다.'),
    ],
    'Music': [
        ('available','доступный','이용 가능한',
         'The album is available in stores.','Альбом доступен в магазинах.','그 앨범은 매장에서 구할 수 있습니다.'),
        ('broaden','расширять','넓히다',
         'She wants to broaden her musical taste.','Она хочет расширить свой музыкальный вкус.','그녀는 음악 취향을 넓히고 싶어합니다.'),
        ('category','категория','범주',
         'Jazz is one category of music.','Джаз — одна из категорий музыки.','재즈는 음악의 한 범주입니다.'),
        ('disparate','разнородный','이질적인',
         'The album mixes disparate styles.','Альбом смешивает разнородные стили.','그 앨범은 이질적인 스타일을 섞습니다.'),
        ('divide','делить','나누다',
         'The music was divided into two parts.','Музыка была разделена на две части.','음악은 두 부분으로 나뉘었습니다.'),
        ('favor','предпочитать','선호하다',
         'He favors classical music.','Он предпочитает классическую музыку.','그는 클래식 음악을 선호합니다.'),
        ('instinct','инстинкт','본능',
         'He has an instinct for rhythm.','У него инстинкт к ритму.','그는 리듬에 대한 본능이 있습니다.'),
        ('prefer','предпочитать','선호하다',
         'I prefer live concerts.','Я предпочитаю живые концерты.','나는 라이브 콘서트를 선호합니다.'),
        ('reason','причина','이유',
         'There is no reason to miss the show.','Нет причины пропустить шоу.','그 공연을 놓칠 이유가 없습니다.'),
        ('relaxation','отдых','휴식',
         'Music provides relaxation.','Музыка даёт отдых.','음악은 휴식을 제공합니다.'),
        ('taste','вкус, предпочтение','취향',
         'She has good taste in music.','У неё хороший вкус в музыке.','그녀는 음악 취향이 좋습니다.'),
        ('urge','побуждать','촉구하다',
         'He urged the band to record faster.','Он побуждал группу записываться быстрее.','그는 밴드가 더 빨리 녹음하도록 촉구했습니다.'),
    ],
    'Museums': [
        ('acquire','приобретать','획득하다',
         'The museum acquired a rare painting.','Музей приобрёл редкую картину.','박물관이 희귀한 그림을 획득했습니다.'),
        ('admire','восхищаться','감탄하다',
         'Visitors admire the collection.','Посетители восхищаются коллекцией.','방문객들이 소장품에 감탄합니다.'),
        ('collection','коллекция','소장품',
         'The collection includes ancient art.','Коллекция включает древнее искусство.','소장품에는 고대 미술이 포함됩니다.'),
        ('criticism','критика','비평',
         'The exhibition drew both praise and criticism.','Выставка вызвала и похвалу, и критику.','그 전시는 칭찬과 비평을 모두 불러일으켰습니다.'),
        ('express','выражать','표현하다',
         'The art expresses deep emotion.','Искусство выражает глубокие эмоции.','그 미술은 깊은 감정을 표현합니다.'),
        ('fashion','мода','유행',
         'The style never went out of fashion.','Стиль никогда не выходил из моды.','그 스타일은 유행이 지나지 않았습니다.'),
        ('leisure','досуг','여가',
         'We visited the museum at our leisure.','Мы посетили музей на досуге.','우리는 여가 시간에 박물관을 방문했습니다.'),
        ('respond','отвечать, реагировать','응답하다',
         'Visitors responded well to the exhibit.','Посетители хорошо отреагировали на экспозицию.','방문객들은 전시에 잘 반응했습니다.'),
        ('schedule','планировать','일정을 잡다',
         'The museum scheduled a new tour.','Музей запланировал новую экскурсию.','박물관이 새 투어 일정을 잡았습니다.'),
        ('significant','значительный','중요한',
         'The donation was significant.','Пожертвование было значительным.','기부는 상당했습니다.'),
        ('specialize','специализироваться','전문으로 하다',
         'The museum specializes in modern art.','Музей специализируется на современном искусстве.','그 박물관은 현대 미술을 전문으로 합니다.'),
        ('spectrum','спектр','범위',
         'The gallery covers a wide spectrum of styles.','Галерея охватывает широкий спектр стилей.','그 갤러리는 다양한 스타일 범위를 다룹니다.'),
    ],
    'Media': [
        ('assignment','задание','과제',
         'The reporter is on assignment abroad.','Репортёр в командировке за границей.','기자가 해외 취재 중입니다.'),
        ('choose','выбирать','선택하다',
         'The editor chose the headline.','Редактор выбрал заголовок.','편집자가 헤드라인을 선택했습니다.'),
        ('constant','постоянный','꾸준한',
         'The station gets constant news updates.','Станция получает постоянные обновления новостей.','방송국은 꾸준한 뉴스 업데이트를 받습니다.'),
        ('constitute','составлять','구성하다',
         'Investigative stories constitute most of the program.','Расследовательские репортажи составляют большую часть программы.','취재 보도가 프로그램의 대부분을 구성합니다.'),
        ('decisive','решающий','결정적인',
         'The editor made a decisive call.','Редактор принял решающее решение.','편집자가 결정적인 판단을 했습니다.'),
        ('disseminate','распространять','퍼뜨리다',
         'The network disseminates news worldwide.','Сеть распространяет новости по всему миру.','네트워크가 전 세계로 뉴스를 퍼뜨립니다.'),
        ('impact','влияние','영향',
         'The report had a strong impact.','Репортаж оказал сильное влияние.','그 보도는 큰 영향이 있었습니다.'),
        ('in depth','углублённый','심층적인',
         'The program covers the story in depth.','Программа глубоко освещает эту историю.','그 프로그램은 그 사건을 심층적으로 다룹니다.'),
        ('investigative','расследовательский','취재의',
         'She works in investigative journalism.','Она работает в расследовательской журналистике.','그녀는 탐사 저널리즘 분야에서 일합니다.'),
        ('link','связывать','연결하다',
         'The article links the two events.','Статья связывает два события.','기사가 두 사건을 연결합니다.'),
        ('subscribe','подписываться','구독하다',
         'Thousands subscribe to the news service.','Тысячи подписываются на новостной сервис.','수천 명이 그 뉴스 서비스를 구독합니다.'),
        ('thorough','тщательный','철저한',
         'The magazine did a thorough review.','Журнал провёл тщательный обзор.','그 잡지가 철저한 리뷰를 했습니다.'),
    ],
    'Doctors Office': [
        ('annually','ежегодно','매년',
         'You should have a checkup annually.','Вам следует проходить осмотр ежегодно.','매년 건강검진을 받아야 합니다.'),
        ('appointment','приём, запись','진료 예약',
         'I made an appointment for Monday.','Я записался на приём на понедельник.','나는 월요일에 진료를 예약했습니다.'),
        ('assess','оценивать','평가하다',
         'The doctor will assess your condition.','Врач оценит ваше состояние.','의사가 당신의 상태를 평가할 것입니다.'),
        ('diagnose','диагностировать','진단하다',
         'The doctor diagnosed the illness.','Врач диагностировал болезнь.','의사가 병을 진단했습니다.'),
        ('effective','эффективный','효과적인',
         'The treatment proved effective.','Лечение оказалось эффективным.','그 치료는 효과적인 것으로 밝혀졌습니다.'),
        ('instrument','инструмент','도구',
         'The doctor used sterile instruments.','Врач использовал стерильные инструменты.','의사가 소독된 도구를 사용했습니다.'),
        ('manage','справляться, управлять','관리하다',
         'She manages her symptoms well.','Она хорошо справляется со своими симптомами.','그녀는 증상을 잘 관리합니다.'),
        ('prevent','предотвращать','예방하다',
         'Good habits prevent illness.','Хорошие привычки предотвращают болезни.','좋은 습관이 질병을 예방합니다.'),
        ('recommendation','рекомендация','권고',
         'Follow the doctor\'s recommendations.','Следуйте рекомендациям врача.','의사의 권고를 따르세요.'),
        ('record','запись','기록',
         'The clinic keeps a record of visits.','Клиника ведёт записи посещений.','클리닉은 방문 기록을 유지합니다.'),
        ('refer','направлять','의뢰하다',
         'The doctor referred me to a specialist.','Врач направил меня к специалисту.','의사가 나를 전문의에게 의뢰했습니다.'),
        ('serious','серьёзный','심각한',
         'It was a serious condition.','Это было серьёзное состояние.','그것은 심각한 상태였습니다.'),
    ],
    'Dentists Office': [
        ('aware','осознающий','인지하는',
         'Be aware of your oral health.','Осознавайте важность здоровья полости рта.','구강 건강을 인지하세요.'),
        ('catch up','наверстать','따라잡다',
         'Patients should catch up on dental visits.','Пациентам стоит наверстать визиты к стоматологу.','환자는 치과 방문을 따라잡아야 합니다.'),
        ('distraction','отвлечение','방해',
         'The office keeps noise as a distraction-free zone.','В кабинете стараются избегать отвлекающих факторов.','그 진료실은 방해 요인이 없도록 합니다.'),
        ('encouragement','ободрение','격려',
         'The dentist gave patients encouragement.','Стоматолог поддерживал пациентов.','치과의사가 환자에게 격려를 주었습니다.'),
        ('evident','очевидный','명백한',
         'Improvement was evident after treatment.','Улучшение было очевидным после лечения.','치료 후 개선이 명백했습니다.'),
        ('habit','привычка','습관',
         'Brushing daily is a good habit.','Ежедневная чистка — хорошая привычка.','매일 양치질하는 것은 좋은 습관입니다.'),
        ('illuminate','освещать','밝히다',
         'The dentist illuminated the mouth to check the teeth.','Стоматолог осветил полость рта, чтобы проверить зубы.','치과의사가 치아를 확인하기 위해 입을 밝혔습니다.'),
        ('irritate','раздражать','자극하다',
         'The gum may irritate sensitive teeth.','Десна может раздражать чувствительные зубы.','잇몸이 민감한 치아를 자극할 수 있습니다.'),
        ('overview','обзор','개요',
         'The dentist gave an overview of the treatment.','Стоматолог дал обзор лечения.','치과의사가 치료 개요를 설명했습니다.'),
        ('position','положение','위치',
         'The position of the tooth is unusual.','Положение зуба необычное.','그 치아의 위치가 특이합니다.'),
        ('regularly','регулярно','정기적으로',
         'Visit the dentist regularly.','Посещайте стоматолога регулярно.','치과에 정기적으로 방문하세요.'),
        ('restore','восстанавливать','회복시키다',
         'The dentist restored the damaged tooth.','Стоматолог восстановил повреждённый зуб.','치과의사가 손상된 치아를 회복시켰습니다.'),
    ],
    'Health Insurance': [
        ('allow','позволять','허용하다',
         'The plan allows two checkups a year.','План позволяет два осмотра в год.','그 보험은 연간 검진 2회를 허용합니다.'),
        ('alternative','альтернатива','대안',
         'The policy offers alternative coverage.','Полис предлагает альтернативное покрытие.','그 보험은 대체 보장을 제공합니다.'),
        ('aspect','аспект','측면',
         'Consider every aspect of the policy.','Учитывайте каждый аспект полиса.','보험의 모든 측면을 고려하세요.'),
        ('assess','оценивать','평가하다',
         'The insurer assessed the claim.','Страховщик оценил претензию.','보험사가 청구를 평가했습니다.'),
        ('concern','беспокойство','우려',
         'Cost is a major concern for members.','Стоимость — главное беспокойство для участников.','비용은 가입자에게 주요 우려 사항입니다.'),
        ('emphasize','подчёркивать','강조하다',
         'The provider emphasized prevention.','Поставщик подчеркнул профилактику.','제공자는 예방을 강조했습니다.'),
        ('incur','нести (расходы)','발생시키다',
         'You may incur extra charges.','Вы можете понести дополнительные расходы.','추가 비용이 발생할 수 있습니다.'),
        ('personnel','персонал','직원',
         'Company personnel get group coverage.','Сотрудники компании получают коллективное покрытие.','회사 직원은 단체 보장을 받습니다.'),
        ('policy','полис, политика','보험 증권',
         'Read the policy before signing.','Прочитайте полис перед подписанием.','서명하기 전에 보험 증권을 읽으세요.'),
        ('portion','часть','부분',
         'The insurer pays a portion of the cost.','Страховщик оплачивает часть стоимости.','보험사가 비용의 일부를 지불합니다.'),
        ('regardless','несмотря на','~와 관계없이',
         'Coverage continues regardless of age.','Покрытие продолжается независимо от возраста.','보장은 나이와 관계없이 계속됩니다.'),
        ('suitable','подходящий','적합한',
         'Find a plan suitable for your needs.','Найдите план, подходящий вашим потребностям.','당신의 필요에 적합한 플랜을 찾으세요.'),
    ],
    'Hospitals': [
        ('admit','принимать (в больницу)','입원시키다',
         'The patient was admitted overnight.','Пациент был госпитализирован на ночь.','환자가 밤새 입원했습니다.'),
        ('authorization','разрешение','승인',
         'The insurer gave authorization for surgery.','Страховщик дал разрешение на операцию.','보험사가 수술을 승인했습니다.'),
        ('designate','назначать, указывать','지정하다',
         'The doctor designated the treatment.','Врач назначил лечение.','의사가 치료를 지정했습니다.'),
        ('escort','сопровождение','안내',
         'An escort led us to the ward.','Сопровождающий провёл нас в палату.','안내자가 우리를 병동으로 안내했습니다.'),
        ('identify','опознавать','확인하다',
         'The bracelet helps identify the patient.','Браслет помогает опознать пациента.','팔찌가 환자를 확인하는 데 도움이 됩니다.'),
        ('mission','миссия','사명',
         'Our mission is patient care.','Наша миссия — забота о пациентах.','우리의 사명은 환자 돌봄입니다.'),
        ('permit','разрешать','허가하다',
         'Visiting is not permitted after 8.','Посещения не разрешены после 8 часов.','8시 이후에는 방문이 허가되지 않습니다.'),
        ('pertinent','относящийся к делу','관련 있는',
         'Give the doctor all pertinent information.','Дайте врачу всю относящуюся к делу информацию.','의사에게 관련 정보를 모두 주세요.'),
        ('procedure','процедура','절차',
         'The procedure is standard.','Процедура стандартная.','그 절차는 표준입니다.'),
        ('result','результат','결과',
         'The test results came back.','Пришли результаты анализов.','검사 결과가 나왔습니다.'),
        ('statement','заявление, выписка','명세서',
         'The hospital sent a billing statement.','Больница прислала счёт.','병원이 청구 명세서를 보냈습니다.'),
        ('usual','обычный','평소의',
         'We followed the usual procedure.','Мы следовали обычной процедуре.','우리는 평소 절차를 따랐습니다.'),
    ],
    'Pharmacy': [
        ('consult','консультироваться','상담하다',
         'Consult the pharmacist about the drug.','Проконсультируйтесь с фармацевтом насчёт лекарства.','약에 대해 약사와 상담하세요.'),
        ('control','контролировать','통제하다',
         'The pharmacy controls its inventory.','Аптека контролирует свои запасы.','약국이 재고를 통제합니다.'),
        ('convenient','удобный','편리한',
         'The pharmacy has convenient hours.','У аптеки удобные часы работы.','그 약국은 영업 시간이 편리합니다.'),
        ('detect','обнаруживать','감지하다',
         'The test detects the condition early.','Тест обнаруживает состояние на ранней стадии.','그 검사는 상태를 조기에 감지합니다.'),
        ('factor','фактор','요인',
         'Dosage depends on several factors.','Дозировка зависит от нескольких факторов.','복용량은 여러 요인에 달려 있습니다.'),
        ('interaction','взаимодействие','상호작용',
         'Ask about drug interactions.','Спросите о взаимодействии лекарств.','약물 상호작용에 대해 물어보세요.'),
        ('limit','предел','한도',
         'There is a limit on refills.','Есть предел на повторные выдачи.','리필에는 한도가 있습니다.'),
        ('monitor','отслеживать','모니터링하다',
         'Monitor your reaction to the medicine.','Отслеживайте свою реакцию на лекарство.','약에 대한 반응을 모니터링하세요.'),
        ('potential','потенциальный','잠재적인',
         'The drug has potential side effects.','У лекарства есть потенциальные побочные эффекты.','그 약에는 잠재적인 부작용이 있습니다.'),
        ('sample','образец','표본',
         'The pharmacist gave a free sample.','Фармацевт дал бесплатный образец.','약사가 무료 표본을 주었습니다.'),
        ('sense','чувство','감각',
         'Use common sense with dosage.','Пользуйтесь здравым смыслом при дозировке.','복용량에 상식을 사용하세요.'),
        ('volunteer','доброволец','자원봉사자',
         'Volunteers help distribute the medication.','Добровольцы помогают раздавать лекарства.','자원봉사자들이 약품 배포를 돕습니다.'),
    ],
}

def main():
    data = json.load(open(SRC, encoding='utf-8'))
    cat_order = list(dict.fromkeys(w['category'] for w in data))

    for cat, rows in BOOK.items():
        if cat not in cat_order:
            print('!! unknown category:', cat); continue
        new_cards = [card(cat, *r) for r in rows]
        data = [w for w in data if w['category'] != cat]
        data.extend(new_cards)

    # re-sort to original category order (preserve insertion within category)
    rank = {c: i for i, c in enumerate(cat_order)}
    pos = {id(w): i for i, w in enumerate(data)}
    data.sort(key=lambda w: (rank[w['category']], pos[id(w)]))

    # validation
    counts = Counter(w['category'] for w in data)
    bad = {c: n for c, n in counts.items() if n != 12}
    if bad:
        raise SystemExit('bad counts: %r' % bad)
    ids = [w['id'] for w in data]
    assert len(ids) == len(set(ids)), 'duplicate ids'
    assert all(w['rus'] == w['correct'] for w in data)
    assert all(w['rus'].strip() and w['kor'].strip() for w in data)

    with open(SRC, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    with open('public/words_optimized.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print('Total:', len(data))
    print('Unique eng:', len(set(w['eng'] for w in data)))
    for cat in cat_order:
        print(f"  {counts[cat]:3}  {cat}")

if __name__ == '__main__':
    main()
